### ISSUE TITLE
No Chinese in "welcome-text-order"

### ISSUE THREAD

**Issue by xingjiapeng** [distrochooser/distrochooser#100]
https://github.com/distrochooser/distrochooser/blob/2df9f37c13c0d3ab54da280dfced8fe1ba685227/backend/locale/cn.po#L83

https://github.com/distrochooser/distrochooser/blob/2df9f37c13c0d3ab54da280dfced8fe1ba685227/backend/locale/en.po#L83

I found there's no Chinese word in this line, what's wrong? Thanks.

![](https://img.vim-cn.com/81/c2f3b931a82dca12e1176207d52aff483e12f3.png)

**Comment by cmllr** [comment]
I think it's because in line 82 is a " missing. I'll take a look on it later this day and deploy an update. Thanks for the hint!

**Comment by cmllr** [comment]
Hello, the fix was deployed and the translation is now displayed. 

Thanks again for your feedback!
