### ISSUE TITLE
Translation: Capital language name

### ISSUE THREAD

**Issue by explorer422** [distrochooser/distrochooser#106]
I am now working on the Traditional Chinese translation of the project. And in the backend/locale/en.po line 97,98 and between 682 to 686:

`97 msgid "locale-link-en"`
`98 msgstr "This text is available in english"`

`682 msgid "locale-en"`
`683 msgstr "english"`
`685 msgid "locale-de"`
`686 msgstr "deutsch"`

Should the *english* be *English* and *deutsch* be *Deutsch* ?
And I also found that some aren't capital yet. But I am not exactly sure where these lines of code are located in the repo.
![ ](https://abload.de/img/screenshot_20201129_287juu.png)

**Comment by cmllr** [comment]
hey, sorry for my late response, I think my mix up of capitalization was not on purpose. The translations of this repository will be included in the upcoming version (https://beta.distrochooser.de), so the exact values causing that mix-up won't be used after the major update.
