### ISSUE TITLE
The order makes little sense.

### ISSUE THREAD

**Issue by igwigg** [distrochooser/distrochooser#108]
When you get your result, the first recommendation is listed correctly. 
After that, however, the various distros appear in an unreasonable order. 
At first, distros are shown which contain negative points, before suddenly a distro appears again without any negative points, which should actually be much higher in the list.
As an example here is a test result: https://beta.distrochooser.de/de/d555dd2f5e/

**Comment by cmllr** [comment]
Sort order is now calculated differently. 

Keep in mind that the order can differ when an answer was important. This causes an answer to count double.
