### ISSUE TITLE
NixOS

### ISSUE THREAD

**Issue by davidak** [distrochooser/distrochooser#116]
**Describe the bug**
The name is written as "nixOS", but it's actually called "NixOS".

Also a Link is missing. Please use https://nixos.org/

seen in beta

![Screenshot from 2021-03-01 10-11-24](https://user-images.githubusercontent.com/91113/109475871-83bf1600-7a76-11eb-8ad4-1786fb56f2b7.png)

**Comment by cmllr** [comment]
Hey, thank you for the info, I applied a fix on the  beta!
