### ISSUE TITLE
Incorrect labels on distro recommendation ❤/👎 buttons

### ISSUE THREAD

**Issue by ThatsNoMoon** [distrochooser/distrochooser#117]
**Describe the bug**
In the beta version of the site, the heart and thumbs down buttons have the same label, referring to giving the recommended distribution a thumbs up.

**To Reproduce**
1. Answer at least one question in the beta version of the quiz.
2. Go to the results.
3. Hover over the heart or thumbs down buttons.

**Expected behavior**
👎 should say something about not liking this distro and giving it a thumbs down. ❤ should say something about giving it a heart, not a thumbs up.

**Screenshot**
![image](https://user-images.githubusercontent.com/25443950/110732465-7413a000-81e1-11eb-94c9-745e9b7d4d57.png)
![image](https://user-images.githubusercontent.com/25443950/110732362-49294c00-81e1-11eb-9810-3af922596f3b.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 86

**Comment by cmllr** [comment]
Hey, thank you for that report. I applied a fix which will go live with the next update run!
