### ISSUE TITLE
Beta answers should appear in logical order

### ISSUE THREAD

**Issue by jmilik** [distrochooser/distrochooser#119]
**Is your feature request related to a problem? Please describe.**
The order of the answers in beta is less clear than the prescribed order in release version.

**Describe the solution you'd like**
Order of answers in beta should be the same as in release.

**Describe alternatives you've considered**
n/a

**Additional context**
![Order of answers does not make sense](https://user-images.githubusercontent.com/39600883/111903612-1716b600-8a3b-11eb-81b5-175970aa4b08.png)

**Comment by cmllr** [comment]
Hey, thank you for your hint. I added an order flag to the answers which will be applied on the next update run.
