### ISSUE TITLE
Suggests several 64-bit only distributions when 32-bit hardware is suggested

### ISSUE THREAD

**Issue by a-hurst** [distrochooser/distrochooser#123]
On the beta site, I filled out the quiz to see what it recommended for the old 32-bit Dell D420 I've been playing around with. Given that lots of distros have been dropping 32-bit support in recent years, I was curious to see what I'd be recommended as options. 

While the results page correctly put a red X beside a few distributions for lack of 32-bit support (e.g. Arch), it failed to do the same for several others. The ones I caught were Qubes OS, Manjaro, elementaryOS and maybe Xubuntu (like Ubuntu, 18.04 LTS still supports 32-bit even though later releases don't).

Obviously keeping track of which distros do and don't support certain architectures is a ton of work, so maybe there's an existing database of up-to-date Linux distro information from which 32-bit (or ARM) status could be fetched automatically?

**Comment by cmllr** [comment]
Hey @a-hurst, do you still have the result link in reach? Then I could take a look on this. 

But I think I just need to update the matrix here, so I will anyways take a look on it to reflect the current distribution situations.

**Comment by a-hurst** [comment]
Hi @cmllr, thanks for taking a look! Here's a link to the results I got: https://beta.distrochooser.de/en/f58f157342/

Like I said, I get the 32-bit warning for some (e.g. Arch) but not for others (e.g. Manjaro).

**Comment by cmllr** [comment]
I updated the matrix, following distribution now recieve a negative point if the old computer option is checked: 

- Manjaro
- Pop!_OS
- Artix
- Qube OS
- Elementary OS
- Fedora
- CentOS
- PCLinuxOS
- Solus
- Linux Mint
- Tails
- Ubuntu

Information is based on the download pages of the distributions or announcement articles about dropping or limiting the support. 

In case of Ubuntu and it's derivates there is still the option to download older/ releases with 32 bit, but as this require to maintain parallel distribution entries in the Distrochooser here, I decided to not include them. Also this would just confuse the user to see several Ubuntu's, for example.
