### ISSUE TITLE
Language switching does not work via option box

### ISSUE THREAD

**Issue by doamatto** [distrochooser/distrochooser#128]
**Describe the bug**
When trying to change the language to another language (say French), it does not change it via the option box. You have to add it to the url instead (in this case, the full URL is `beta.distrochooser.de/fr`).

**To Reproduce**
1. Head to the homepage
2. Try changing the language via the option box
3. Site stays in that language and doesn't redirect/change locales

**Expected behavior**
Switch to the language selected in the option box

**Desktop (please complete the following information):**
 - OS: Windows 10 (19043.1055)
 - Browser Edge/Chrome
 - Version 91.0.864.48

**Additional context**

**Comment by cmllr** [comment]
Hey, thank you for your bug report.  I deployed a fix for that on https://beta.distrochooser.de
