### ISSUE TITLE
options for pop os?

### ISSUE THREAD

**Issue by IrenvanderBeekPXL** [distrochooser/distrochooser#129]
**Is your feature request related to a problem? Please describe.**
I tried letting it say pop os by telling everything about pop, but it didn't gave that option

**Describe the solution you'd like**
I would like pop os being added to distrochooser

**Comment by doamatto** [comment]
Should be closed in favour of #94.

**Comment by cmllr** [comment]
Hey, thank you for your feedback. Pop!_OS was added in commit https://github.com/distrochooser/distrochooser/commit/dfddeabbcf0e6bda69a7cd71a1756ff3d37a6c31
