### ISSUE TITLE
Debian in CentOS description

### ISSUE THREAD

**Issue by JumiDeluxe** [distrochooser/distrochooser#132]
**Describe the bug**
Wrong CentOS description

**To Reproduce**
1. Claim that you prefer fast updates instead of stability
2. View results
3. Find CentOS and read description

**Expected behavior**
"**Debian** updates are usually slow in favor of stability" is not in CentOS description

**Screenshots**
![](https://imgur.com/usl0W6J.png)

**Comment by cmllr** [comment]
Hey @JumiDeluxe, thank you for your feedback!

I've just updated the decision matrix to prevent this text from being used for CentOS!
