### ISSUE TITLE
All the arrow icons should be flipped in the RTL version

### ISSUE THREAD

**Issue by omeritzics** [distrochooser/distrochooser#136]
**Describe the bug**
All the arrow icons should be flipped in the RTL version.

**Screenshot**
![image](https://user-images.githubusercontent.com/66558205/144715633-c282ffa5-d53f-4a08-8cab-11aba47126b7.png)

**Additional context**
Thank you very much again for adding RTL support :)

**Comment by cmllr** [comment]
Hey, thank you for the information, I will add a corresponding fix in the next days.

**Comment by omeritzics** [comment]
Thank you. Additionally, the progress bar should be on the right (but keeping it on the left does not affect the user experience).
