### ISSUE TITLE
Distributions which dropped out 32bit

### ISSUE THREAD

**Issue by ghost** [distrochooser/distrochooser#146]
**Describe the bug**
Hi, there are still some distributions which are listed as distributions supporting 32bit architecture, althought they dropped out 32bit support.

**The distributions are:**
1. elementary OS
2. Xubuntu
3. Ubuntu MATE
4. Kubuntu
5. Solus
6. CentOS
7. Manjaro
8. (RHEL may dropped out 32bit architecture too)

**Comment by cmllr** [comment]
hey, thank you for that list. I will apply that at the next update!

**Comment by cmllr** [comment]
Changes are represented in the decision matrix.
