### ISSUE TITLE
The checkboxes should be in the right of the option texts in RTL mode

### ISSUE THREAD

**Issue by omeritzics** [distrochooser/distrochooser#147]
**Describe the bug**
The checkboxes should be in the right of the option texts, and they are now in the left of them.

**Expected behavior**
The checkboxes should be in the right of the option texts in RTL mode.

**Screenshot**
![distrochooser-rtl](https://user-images.githubusercontent.com/66558205/148654094-e8110e90-9512-4ddd-b237-4490f5fab213.png)

**Additional context**
Related: #130

**Comment by cmllr** [comment]
Thank you, I will fix that at the weekend.
