### ISSUE TITLE
Artix Linux is described wrong

### ISSUE THREAD

**Issue by puyoxyz** [distrochooser/distrochooser#151]
![image](https://user-images.githubusercontent.com/15311104/149056483-ca09f812-fd95-41b2-a696-2ab452403a26.png)

> Artix is an Arch Linux based distribution which utilizes OpenRC instead of systemd.

This is only true if you use the *OpenRC flavor of Artix*. Artix has 4 init system choices: OpenRC, runit, s6, and suite66.

> Majority of configuration is done using shell commands

This is only true if you use a *base ISO*. But those aren't the only ones that Artix offers. From the [Artix download page](https://artixlinux.org/download.php):

> Base ISOs allow for a fully customised installation, which is done in a TTY and is intended for knowledgeable users. This is the recommended way of installing Artix and the team will be happy to support any issue. An almost identical lowmem version found at the testing section below, can boot and install on machines with as little as 300MB of RAM.
> 
> Graphical installation images come with a slightly preconfigured desktop system (LXQt, LXDE, MATE, Cinnamon, KDE/Plasma, XFCE) and a basic set of applications: a file manager, a media player (mpv), a network manager, a document viewer, a web browser and the calamares installer. People afraid of the Linux terminal or in need of a quick, intuitive installation would want this ISO. Support will be provided, if asked nicely and politely.
> 
> The community ISO images are created by individual Artix developers and come in 2 flavours: GTK and Qt. The main environment is MATE and KDE/Plasma respectively, but they also provide LXDE and LXQt as lightweight alternatives. These images contain a complete set of applications for general desktop use, especially KDE/Plasma. They are generally well-tested but provided without official support. Recommended for users that want a fully preconfigured desktop that Just Works™ and/or are too busy to set it up themselves.

**Comment by cmllr** [comment]
I will change this at the weekend. Thank you for the information!

**Comment by cmllr** [comment]
Sorry, this took longer than expected. I updated the translation and the decision matrix.
