### ISSUE TITLE
`~/mixins/bridge` does not appear to be included in the repository

### ISSUE THREAD

**Issue by trickypr** [distrochooser/distrochooser#153]
**Describe the bug**
The page `_language/_slug.vue` in `viisi/` depends on the file `~/mixins/bridge` (`viisi/mixins/bridge.js`), but it doesn't appear to be committed. As it is not in any gitignore file, I assume this is unintentional. 

**To Reproduce**
1. Clone the repo to an empty folder
2. Create `viisi/distrochooser.json` and add the contents `{"frontend": {"backendUrl": "https://waldorf5.distrochooser.de/","frontendUrl": "localhost:3000/","socialNetworks": []}}`
3. Run `yarn`
4. Run `yarn dev`
5. See the behavior

**Expected behavior**
Either `viisi/mixins/bridge.js` should be committed or it should be removed from `_slug.vue`, along with `this.checkForRedirect()` or `viisi/mixins/bridge.js` should be committed to the git repository. 

**Desktop (please complete the following information):**
 - OS: Manjaro \w KDE
 - Version: Commit `0971dcf`
 - Yarn: `1.22.17`
 - Node: `v17.3.0`

**Additional context**
`bridge.js` can be created and the following content added as a work around:
```js
export default {
  created: () => {},
  methods: { checkForRedirect: () => {} },
}
```

**Comment by cmllr** [comment]
`mixins/bridge` was indeed not added by mistake. But as for now, it does not serve any purpose anymore (it was meant to redirect distrochooser 4 results to the legacy domain). I wil fix that at the weekend.
