### ISSUE TITLE
choose more questions and answers: Bootloader, Init System, Display Render, Display Manager, Desktop Environments, Package Managers, smartphone/smarttvs with linux or no

### ISSUE THREAD

**Issue by rodriguezbrown** [distrochooser/distrochooser#180]
**Is your feature request related to a problem? Please describe.**
I wish the distrochooser quiz had more questions about these themes/topics/subjects: Bootloader, Init System, Display Render, Display Manager, Desktop Environments, Package Managers.

**Describe the solution you'd like**
I wish the distrochooser quiz had more questions about these themes/topics/subjects: 
- Bootloader: GRUB etc
- smartphone with linux: firefox os, kai-os, [Ubuntu Touch](https://ubports.com/), android, CalyxOS, Replicant, Sailfish OS, LineageOS,  Librem 5, PinePhone, pure-os, plasma-mobile, postmarketOS, mobian etc or no
- smart-tvs with linux: [webOS](https://github.com/webosose) etc
- support tablet linux: [jingos](https://en.jingos.com/) etc
- Init System: systemd etc
- Display Render: Xorg etc
- Display Manager:  SDDM/GDM etc
- Desktop Environments: GNOME, KDE, XFCE, MATE, Xfce, Cinnamon, Window Managers, Jade, LXDE, Pantheon, Enlightenment, Deepin, LXQT, Cinnamon, AtomOS Desktop Environment etc 
- Package Managers: *APT - Debian distros apt install programname*,  *DNF / YUM - RHEL distros dnf install programname*, *Pacman - Arch distros pacman -S programname* etc.

**Describe alternatives you've considered**
![image](https://user-images.githubusercontent.com/108383570/178116411-2f806249-420d-432c-901c-dc32c1698ea3.png)

**Additional context**
- https://christitus.com/choose-linux-distro/
- https://www.geeksforgeeks.org/linux-distribution-shall-choose/
- https://twitter.com/eXtern_OS
- https://web.archive.org/web/20170930183212/https://externos.io/
- https://www.makeuseof.com/check-which-desktop-environment-you-are-using-linux/
- https://en.cutefishos.com/
- https://github.com/ruslang02/atomos
- https://en.wikipedia.org/wiki/Desktop_environment
- https://itsfoss.com/best-linux-desktop-environments/
- https://tecadmin.net/best-linux-desktop-environments/
- https://www.computerhope.com/jargon/d/desktop-environment.htm
- https://www.youtube.com/watch?v=b5XqwNrOWK0
- https://www.youtube.com/watch?v=at4HNRLDERs
- https://linuxnewbieguide.org/overview-of-chapters/chapter-3-choosing-a-linux-distribution/
- https://www.forbes.com/sites/jasonevangelho/2018/11/27/choosing-linux-2-awesome-tools-to-find-your-perfect-linux-os/?sh=65161f6c3beb
- https://alternativeto.net/software/distro-chooser-de/
- https://livecdlist.com/
- https://alternativeto.net/software/the-livecd-list/about/
- https://www.youtube.com/watch?v=Azh3-ZfUq5Q
- https://librehunt.org/
- https://www.reddit.com/r/FindMeADistro/
- https://github.com/webosose
- https://linuxnewbieguide.org/overview-of-chapters/chapter-3-choosing-a-linux-distribution/
- https://www.techradar.com/best/best-linux-distros
- https://itsfoss.com/linux-phones/
- https://www.howtogeek.com/790014/are-there-any-linux-phones/
- https://www.makeuseof.com/tag/linux-smartphone-operating-systems/
- https://www.youtube.com/watch?v=o9Nq1Reu0Wg
- https://geekflare.com/linux-desktop-environment/
- https://www.omgubuntu.co.uk/2019/07/meet-the-jade-desktop-environment-for-linux-a-shell-built-using-web-tech
- https://en.wikipedia.org/wiki/Firefox_OS
- https://www.youtube.com/watch?v=rZugAfhWkPA
- https://www.youtube.com/watch?v=GSudn0qB6u0
- https://ubuntu-web.org/
- https://www.youtube.com/watch?v=EawS7CAUrf8
- https://www.makeuseof.com/ubuntu-web-chrome-os-alternative/
- https://www.emerald.com/insight/content/doi/10.1108/07378830010314519/full/html
- https://link.springer.com/article/10.1007/s10664-006-9000-x
- http://www.cse.hcmut.edu.vn/~hungnq/courses/nap/alp.pdf
- https://geekflare.com/linux-desktop-environment/
- https://itsfoss.com/best-linux-beginners/
- https://itsfoss.com/best-linux-distributions/
- https://www.techradar.com/best/best-linux-distros
- https://wiki.archlinux.org/title/display_manager
- https://www.linuxjournal.com/content/6-best-linux-desktop-environments-try-2022
- https://itsfoss.com/best-linux-beginners/
- https://itsfoss.com/best-linux-distributions/
- https://www.techradar.com/best/best-linux-distros

**Comment by rodriguezbrown** [comment]
#### questions
1. are you looking for a linux distro that has tablet support? (yes|no)
|> jingos etc. (show this is option)
2. are you looking for a linux distro that has smart-tv support? (yes|no)
|> [webOS](https://github.com/webosose) etc. (show this is option)
3. are you looking for a linux distro that has smartphone? (yes|no)
|___>  firefox os. (show this is option)
|___>  kai-os. (show this is option)
|___>  [Ubuntu Touch](https://ubports.com/). (show this is option)
|___>  Android. (show this is option)
|___>  CalyxOS. (show this is option)
|___>  Replicant. (show this is option)
|___>  Sailfish OS. (show this is option)
|___>  LineageOS. (show this is option)
|___>  Librem 5. (show this is option)
|___>  PinePhone. (show this is option)
|___>  pure-os. (show this is option)
|___>  plasma-mobile. (show this is option)
|___>  postmarketOS. (show this is option)
|___>  mobian etc. (show this is option)
4. are you looking for a linux distro that has desktop environment support?
|___> GNOME. (show this is option)
|___> KDE. (show this is option)
|___> XFCE. (show this is option)
|___> MATE. (show this is option)
|___> Cinnamon. (show this is option)
|___> Window Managers
|___> Jade. (show this is option)
|___> LXDE. (show this is option)
|___> Pantheon. (show this is option)
|___> Enlightenment. (show this is option)
|___> Deepin. (show this is option)
|___> LXQT. (show this is option)
|___> Cinnamon. (show this is option)
|___> AtomOS Desktop Environment etc. (show this is option)
5. are you looking for a linux distro that has Bootloader support?
|___> GRUB etc. (show this is option)
6. are you looking for a linux distro that has Display Render support?
|___> Xorg etc. (show this is option)
|___> Wayland etc. (show this is option)

Wayland

**Comment by cmllr** [comment]
Thank you for this _large_ list of sources and ideas.

**Comment by rodriguezbrown** [comment]
@cmllr some of these questions are for advanced users who are unsure which distro to choose. - the famous: distro hopping
