### ISSUE TITLE
[Suggestion] Use external websites to help translators with their work

### ISSUE THREAD

**Issue by WX4300** [distrochooser/distrochooser#190]
Hi, i really like the idea of your website but maybe you should consider using a website like this one: https://hosted.weblate.org/ to get more translations (maybe also to attract more attention to the website)?

**Comment by cmllr** [comment]
Instance is running on translate.distrochooser.de and instructions can be seen on https://github.com/distrochooser/translations.

Thanks again for the suggestion and the polish translation :)!
