### ISSUE TITLE
[Suggestion] User experience section - An option to pick your favorite distro as a consumption need

### ISSUE THREAD

**Issue by ghost** [distrochooser/distrochooser#194]
**Is your feature request related to a problem? Please describe.**
One of Linux's problems is its fragmentation, I wonder if there wouldn't be a more logical choice based on the type of device the user wants to have or according to his consumption needs.

**Describe the solution you'd like**
If user selects smart-tv, smartphone, tablet, networking(iot), smartwatch, router or notebook image, display corresponding distro.

**Describe alternatives you've considered**
An alternative to solve this problem is to show the user 7 types of options: networking(iot), smart-tv, smartwatch, smartphone, notebook, router or tablet. Each of these devices can have Linux or not, it will depend on the user's response.

**Additional context**

#### 1. concept
![image](https://user-images.githubusercontent.com/111701513/210031193-915a3d2b-291b-4937-bc8a-605c4749cf7e.png)

**1.1. Image-description**

**example 1.1.2: do you have smart-tv?**

> are you looking for a linux distro that has smart-tv support? (yes|no)
|> [webOS](https://github.com/webosose) etc. (show this is option)

**example 1.1.3: do you have smartphone?**

> are you looking for a linux distro that has smartphone support? (yes|no)
|> firefox os. (show this is option with gif or screenshot)
|> Remix-OS. (show this is option with gif or screenshot)
|> kai-os. (show this is option with gif or screenshot)
|> Ubuntu Touch. (show this is option with gif or screenshot)
|> Luas. (show this is option with gif or screenshot)
|> AsteroidOS. (show this is option with gif or screenshot)
|> Android(Google Company). (show this is option with gif or screenshot)
|> CalyxOS. (show this is option with gif or screenshot)
|> LuneOS. (show, this is option with gif or screenshot)
|> Replicant. (show this is option with gif or screenshot)
|> Sailfish-os. (show this is option with gif or screenshot)
|> /e/OS. (show this is option with gif or screenshot)
|> LineageOS. (show this is option with gif or screenshot)
|> Librem 5(Purism Company). (show this is option with gif or screenshot)
|> PinePhone. (show this is option with gif or screenshot)
|> Manjaro Mobile (show this is option with gif or screenshot)
|> HavoOS (show this is option with gif or screenshot)
|> pure-os. (show this is option with gif or screenshot)
|> plasma-mobile. (show this is option with gif or screenshot)
|> AvMultiPhone(Mate-on-phone-desktop). (show this is option with gif or screenshot)
|> postmarketOS. (show this is option with gif or screenshot)
|> SHR. (show this is option with gif or screenshot)
|> mobian. (show this is option with gif or screenshot)
|> FairPhoneOS. (show this is option with gif or screenshot)
|> Volla Phone. (show this is option with gif or screenshot)
|> Pro1 X(F(x)tec). (show this is option with gif or screenshot)
|> Tizen(Linux Foundation). (show this is option with gif or screenshot)
|> Maemo. (show this is option with gif or screenshot)
|> Droidian. (show this is option with gif or screenshot)
|> GrapheneOS. (show this is option with gif or screenshot)
|> Nemo Mobile. (show this is option with gif or screenshot)
|> ExpidusOS. (show this is option with gif or screenshot)
|> NixOS. (show this is option with gif or screenshot)

**example 1.1.4: do you have notebook?**

> are you looking for a linux distro that has notebook support? (yes|no)
|> Ubuntu. (show this is option with gif or screenshot)

**example 1.1.5: do you have tablet?**

> are you looking for a linux distro that has tablet support? (yes|no)
|> jingos etc. (show this is option)

**example 1.1.6: do you have smartwatch?**

> are you looking for a linux distro that has smartwatch support? (yes|no)
|> Wear-os etc. (show this is option)

#### 2. Idea
You could select a more or less popular distro based on x amount of device types it is compatible with, for example, assess whether a linux distro is available on smartphone, tablet, smart-tv etc.

#### 3. reference
- https://github.com/distrochooser/distrochooser/issues/180

**Comment by cmllr** [comment]
Thanks for this idea and the effort to define this issue.

Distrochooser focuses entirely on desktop/ notebook distributions. Advanced topics, such as router OS or smartphone operating systems are mostly left out to keep an focus which is maintainable for me.  

So I think that the only hardware-based decision should be done between notebooks and stationary computers, leaving out other hardware classes. Realistically, this would be an extension for the "hardware" question

**Comment by cmllr** [comment]
> Hi.
> 
> > Thanks for this idea and the effort to define this issue.
> > Distrochooser focuses entirely on desktop/ notebook distributions. Advanced topics, such as router OS or smartphone operating systems are mostly left out to keep an focus which is maintainable for me.
> > So I think that the only hardware-based decision should be done between notebooks and stationary computers, leaving out other hardware classes. Realistically, this would be an extension for the "hardware" question
> 
> An idea: depending on the size of the screen that the user accesses the distrochooser site, one of these options may appear. For example, if you use mobile - it would make sense to display distros that work on your smartphone. If the user accesses the site through the desktop, then display distros to install on the computer.
> 
> Perhaps this issue is related to this other issue: [question for touch screens and hidpi screens](https://github.com/distrochooser/distrochooser/issues/160), [Improve UX on mobile devices](https://github.com/distrochooser/distrochooser/issues/143)

Hey @eantho!

Distrochooser does not feature certain smartphone distros. Only considering screen width might also lead to false assumptions about the user desired platform. 

#220 adds an transparent step into the question process where the user will be able to set certain flags, such as touch, mobile device and others (such as hardware specs), which is in my opinion a better way instead of deriving result limiting criteria from the user device.

**Comment by cmllr** [comment]
> > [#220](https://github.com/distrochooser/distrochooser/pull/220) adds an transparent step into the question process where the user will be able to set certain flags, such as touch, mobile device and others (such as hardware specs), which is in my opinion a better way instead of deriving result limiting criteria from the user device.
> 
> I wonder if it would be possible to add this media type flag: CD, DVD, USB, Flash Drive or architecture: x86, x86-64 etc. Would it be possible to add this media type flag: CD, DVD, USB, Flash Drive or architecture: x86, x86-64 etc?
> 
> (For example, there is a site that has media type flag information on the livecd distro)
> 
> ![image](https://user-images.githubusercontent.com/126544812/221951280-27366005-cd2b-4527-8056-6d9dbe20ab5d.png)
> 
> Another important metric would be whether the linux distro has a livecd/live-dvd version or can be booted from an external device such as hd, ssd or pendrive etc. Sites like: `https://livecdlist.com/` or `https://www.linuxliveusb.com/en/supported-linuxes` have this relevant information

Thanks, I moved that into #242 as I think it can be implemented using the changes from #185. But to keep the focus of this issue, any discussion regarding live media and/or architecture selections can be done in #242
