### ISSUE TITLE
add donate button to project

### ISSUE THREAD

**Issue by ghost** [distrochooser/distrochooser#195]
**Is your feature request related to a problem? Please describe.**
Someone might be interested in contributing to the project financially. Maybe this is interesting to pay cloud servers for some ai consumption, cataloging linux distros, open data, research, hosting the distrochooser project website, for api maintenance of distrochooser or information storage only on linux distros.

**Describe the solution you'd like**
Add donate button to project(website).

**Describe alternatives you've considered**
I was thinking of a paypal button to add the donate link.

**Additional context**
![image](https://user-images.githubusercontent.com/111701513/202910877-80467b98-555c-421b-ba7d-4cc833dd2066.png)

As we can see in the image, the user clicks and is redirected to a page where he enters the corresponding donation amount.

**Comment by cmllr** [comment]
Due to tax reasons, I currently don't take any donations. But this might change somewhere next year.

**Comment by allonkeyns** [comment]
Hello everyone.

I know this question is closed, but I have a similar doubt: I would like to know if you all ever thought about one day considering integrating Gitpay with distrochooser. Have you all ever thought of one day considering integrating Gitpay with distrochooser?

an idea: Gitpay is a platform that allows you to collaborate with other developers and earn bounties for solving issues from projects. You can also create your own projects and invite other developers to collaborate with you.
