### ISSUE TITLE
[Suggestion] choose linux distro by hardware compatibility or well-known company of the hardware

### ISSUE THREAD

**Issue by codehangen** [distrochooser/distrochooser#197]
**Is your feature request related to a problem? Please describe.**
This request is related to the issue: "metrics in distrochooser" in [[Suggestion] metrics for distrochooser](https://github.com/distrochooser/distrochooser/issues/200) and "an option to pick your favorite distro as a consumption need in distrochooser" in [[Suggestion] User experience section - An option to pick your favorite distro as a consumption need](https://github.com/distrochooser/distrochooser/issues/194) and issue: "prefer mainstream distributions over the smaller ones" in [[Suggestion] Prefer mainstream distributions over the smaller ones](https://github.com/distrochooser/distrochooser/issues/193)

**Describe the solution you'd like**
So... I will comment on every feedback I received - and "the solution" I considered here.

> "Distrochooser focuses entirely on desktop/ notebook distributions. Advanced topics, such as router OS or smartphone operating systems are mostly left out to keep an focus which is maintainable for me."
> "So I think that the only hardware-based decision should be done between notebooks and stationary computers, leaving out other hardware classes. Realistically, this would be an extension for the "hardware" question"

We can choose the hardware or operating system based on the company that is responsible for that hardware or operating system. Sometimes users choose "linux" because of "Dell" or "System 76". Anyway, I think it's interesting to ask.... the brand... to check if the user has a good knowledge of Linux or not, considering that there is an open question or reactive answer topic.

So... choice "hardware", could be something like:
> Do you know any of these companies that are responsible for hardware or operating system in linux? (discord/discourse/blog/medium/linux-hardware.org etc):
|> System76
|> Tuxedo
|> Slimook 
|> Starlabs
|> RedHat
|> Canonical
|> Dell
|> AMD
|> Intel
|> Gigabyte
|> Lenovo

**Describe alternatives you've considered**
- we can ask a question about hd, ssd, ram memory - and based on that question the user decides the company. And we can check if that company is compatible with the distro linux or not.
- we can see which are the companies or hardware that are most common
- or according to the data of which are the most common companies or hardware. which distros are more or less popular
- we can skip linux distros based on hardware compatibility, if user hardware is not compatible with linux distro, linux distro is skipped
- Another complementary idea would be that you can check if the distro is more or less popular if the distro is compatible with popular drivers from companies like Dell, Apple etc in terms of driver for audio, video, wifi or any technical information like that. For example, if the distro has macbook compatibility and it works. Or does it only work with Dell drivers etc. This can be more or less useful for the user.

**Additional context**
- [linux-hardware.org](https://linux-hardware.org): "This is a project to anonymously collect hardware details of Linux-powered computers over the world and help people to collaboratively debug hardware related issues, check for Linux-compatibility and find drivers."
- [linuxhw/SMART](https://github.com/linuxhw/SMART): "Estimate reliability of desktop-class HDD/SSD drives"

#### question/feedback
*what do you all think of this idea?*

**Comment by cmllr** [comment]
Closing this issue as an approach is discussed with #199
