### ISSUE TITLE
[Suggestion] redesign distrochooser with minimal-ui

### ISSUE THREAD

**Issue by codehangen** [distrochooser/distrochooser#198]
**Is your feature request related to a problem? Please describe.**
I was thinking about doing a distrochooser redesign based on the repository: [github/fatihmeh/choose-your-operating-system](https://github.com/fatihmeh/choose-your-operating-system). And... I was looking to solve this problem here: [github/distrochooser/distrochooser/issues/143](https://github.com/distrochooser/distrochooser/issues/143)

**Describe the solution you'd like**
With the redesign, perhaps distrochooser will work correctly as a web app when accessed via mobile. If you all want to see it working, visit this link: [fatihozcan/choose-your-operating-system](https://www.fatihozcan.dev/choose-your-operating-system/)

#### concept
![image](https://user-images.githubusercontent.com/111701513/207098987-0fb8fed8-9148-48a0-9acb-b6fc93b6a2b0.png)

**image-description:**  As we can see in the image we have a minimal layout, with few options.

**Describe alternatives you've considered**
1. I think it would be interesting to separate a code just html, css, js - from the backend code. *The redesign is only the ui/ux part, that is, the frontend part and not the backend part.*
2. Before sending a PR, I want to listen to some feedback to check if this is possible or not
3. redesign, new ui/ux

**Additional context**
- ui: "The user interface (UI) is the point of human-computer interaction and communication in a device. This can include display screens, keyboards etc".
- ux: "User experience (UX) design is the process design teams use to create products that provide meaningful and relevant experiences to users"
- redesign: "The meaning of redesign is to revise in appearance, function, or content."

**Comment by cmllr** [comment]
I currently do not plan to do a major redesign. While I think *some* parts require redesign, I think I will stick with the current UX structure for now.
