### ISSUE TITLE
[Suggestion] metrics for distrochooser

### ISSUE THREAD

**Issue by ghost** [distrochooser/distrochooser#200]
**Is your feature request related to a problem? Please describe.**
This request is related to the issue: "prefer mainstream distributions over the smaller ones" in [[Suggestion] Prefer mainstream distributions over the smaller ones](https://github.com/distrochooser/distrochooser/issues/193)

**Describe the solution you'd like**
- I would like to offer: a set of ideas, concepts for solving some problems for selecting one or more more or less popular distros in distrochooser. And also, since no one has given feedback, I open an issue here. 
- *So... I will comment on every feedback I received - and "the solution" I considered here.*

**Describe alternatives you've considered**
1. I used screen prototypes, I did more scientific, academic research.
2. I hope to clarify or help in some way 
3. I am sending this new feedback to get new feedback as well.

*message, feedback*

> Hey, thanks for the suggestions!
> And to pick up @codehangen 's ideas here (thanks again for that!):
> 1. GitHub satistics (stars, forks, issues) is a good metric if you compare projects on GitHub only, if a Distro does not use a public GitHub repo this will require an replacement metric
> 2. I would like not to ask for any personal data (mostly because of GDPR hassle)
> 3. I think this could be added to the questionaire as an answer, so this would be easy on the technical side
> 4. 4+5. I like this idea, but I am not entirely commited to this yet. I need to think about this for a bit
> 5. Is already in the making (the thumbs up and down icons). But this mode is not enabled yet as I need to balance it further (as at the moment, for ~1 500 000 results, I only have 15000 votes, which makes this a bit hard to balance)
> I think this is hard to measure and balance

#### 1. problem
> GitHub satistics (stars, forks, issues) is a good metric if you compare projects on GitHub only, if a Distro does not use a public GitHub repo this will require an replacement metric

#### 1.1 answer and concept
As we can see in the image, there are public distrowatch metrics. This can help in selecting a popular or less popular distro(this would be a replacement metric, here in this specific example we can check the metric of the distro being more or less popular with the user rating and the popularity information). 

In addition to GitHub, there are distros that host GitLab, Bitbucket, Source-hut and others(there would have to be an api(official) for each of these platforms). But... if there is no api, it is worth remembering that it is possible to build an api with crawler(which is a program that looks for information in different pages and places to later be stored in some database for consultation.) for this.

![image](https://user-images.githubusercontent.com/111701513/203334842-99cfd59b-0200-4ff1-b77a-6141bcae8130.png) [source: dw-remastered.vercel/distro/popos](https://dw-remastered.vercel.app/distro/popos)

#### 2. problem
> I would like not to ask for any personal data (mostly because of GDPR hassle)

#### 2.1 answer and concept *or*
As we can see in this image, there is a slide in distrochooser where the user can drag and drop whenever they want. This allows directing the user to the corresponding linux distro based on development time. So... Instead of asking for the user's age, it could only ask for linux development time. With that, you could select more or less popular distro... according to the development time compared to other previous distros.
![image](https://user-images.githubusercontent.com/111701513/210027676-eb971167-d7da-4f94-991a-fb80366a1e92.png)

*Please see this: [LinuxTimeline](https://github.com/FabioLolix/LinuxTimeline)*

#### 2.2 answer and concept *or*
This is an interesting option, you could filter newer or older distros by development time. Which is different from the previous case which doesn't have a datetime.
![image](https://user-images.githubusercontent.com/111701513/210027830-c56a1d95-0e5d-4c7c-94c8-3e466780c1b2.png)

#### 2.3 answer and concept *or*
I can here in this conceptual image make a quantitative analysis of linux distros made by a development time, the more or less popular distro will be the one with the longest development time or the shortest development time.
![image](https://user-images.githubusercontent.com/111701513/210038888-e9dd79eb-2fd8-4d75-8ad2-1ba38754cfc0.png)

#### 2.4 answer and concept *or*
For example, in this concept image here I only want the distro developed in my country and not in other countries. Because I can be doing a scientific project of specific development and that must be done or restricted to the technology that my country produces, develops.
![image](https://user-images.githubusercontent.com/111701513/210028058-c1ecdff6-b4fa-47c8-983a-bf36a4feb7ae.png)

#### 2.5 answer and concept *or*
As we can see in this image, another interesting option is to select the distro where it was developed, such as Brazil, United States, etc. A Linux distro can be more or less popular based on the x amount of distros produced by the country, state, city or region, municipality.
![image](https://user-images.githubusercontent.com/111701513/211210119-61b94ed7-ab91-4abc-98c9-66fdaeb680c2.png)

```markdown
// source-code
pie title select the distro by the quantity produced in the country
    "United States of America" : 100
    "Japan" : 80
    "Switzerland" : 15
    "Brazil" : 15
    "Belgium" : 100
    "Japan" : 80
    "Bolivia" : 15
    "Bulgaria" : 15
    "Cape Verde" : 100
    "Cameroon" : 80
    "Canada" : 15
    "China" : 15
```

#### 3. problem
> I think this could be added to the questionaire as an answer, so this would be easy on the technical side: 4+5. I like this idea, but I am not entirely commited to this yet. I need to think about this for a bit.

#### 3.1 answer and concept
In general, this feature involves the idea of ​​ranking the most popular or least popular distro based on some previous answer or some public, private metric for that matter. Or on the other hand, it involves the idea of ​​having some additional layer of question in the previous answer or in another previous or subsequent question as well or answer too.

#### 4. problem
> I think this is hard to measure and balance

#### 4.1 answer and concept
Another complementary idea would be that you can check if the distro is more or less popular if the distro is compatible with popular drivers from companies like Dell, Apple etc in terms of driver for audio, video, wifi or any technical information like that. *For example, if the distro has macbook compatibility and it works. Or does it only work with Dell drivers etc. This can be more or less useful for the user.*

![image](https://user-images.githubusercontent.com/111701513/210042418-acdd57b5-7e1e-4be1-a582-bf98ec5e8874.png)

#### 5. problem
> Is already in the making (the thumbs up and down icons). But this mode is not enabled yet as I need to balance it further (as at the moment, for ~1 500 000 results, I only have 15000 votes, which makes this a bit hard to balance)

#### 5.1 answer and concept: issues
There is this feature request like [Change the questions depending on if they are (linux) beginnner](https://github.com/distrochooser/distrochooser/issues/149), [Add answer defined additional selection layer](https://github.com/distrochooser/distrochooser/pull/185), [Software availability and a way to rank what is more important to the user](https://github.com/distrochooser/distrochooser/issues/138) *(each of these issues if resolved can help this feature overall)*

#### 5.2 answer and concept: forks
Ask if the distro is based on another distro. Generally popular distros are based on popular distros. It's a way to solve this problem here.

![image](https://user-images.githubusercontent.com/111701513/211238426-d67525f7-4938-48d3-b8c9-d61fd67ba8c4.png)

#### 5.3 answer and concept: filters
![image](https://user-images.githubusercontent.com/111701513/210042475-aa4113a4-4f33-403c-bda0-b5c7cb1becfe.png)

**Additional context**
Here is a possible list of metrics in distrochooser:
- [[Suggestion] distrochooser with crawler](https://github.com/distrochooser/distrochooser/issues/213)
- [[Suggestion] apis in distrochooser](https://github.com/distrochooser/distrochooser/issues/212)
- [[Suggestion] distrochooser with version bot](https://github.com/distrochooser/distrochooser/issues/211)
- [[Suggestion] choose linux distro by hardware compatibility or well-known company of the hardware](https://github.com/distrochooser/distrochooser/issues/197)
- [[Suggestion] choose the linux distro by license](https://github.com/distrochooser/distrochooser/issues/202)
- [[Suggestion] User experience section - An option to pick your favorite distro as a consumption need](https://github.com/distrochooser/distrochooser/issues/194)

**Comment by xahodo** [comment]
The problem with the statistics from distrowatch is that they measure clicks, i.e. how many people went to the website of a particular distribution, _not_ actual installs.

A more accurate measurement (with conservative room for error) is to check how many people participate in their communities (lots of work, I know, but it's the better metric). You could check things like irc/matrix logs (for the amount of discussion for the last several days), forums (you could ask the forum _admin_ to do a query on the database for the amount and frequency of user activity in the same amount of time), and reddit (where you just check how many posts there are in their subreddits for the last while).

*LOTS* of work, but it's bound to give more accurate information then just clicks.

**Comment by cmllr** [comment]
I made some tests using the data which is already available in the distrochooser database. For each entry in a result, there can be a positive or a negative vote (or no votes at all). Based on all votes, this allows to calculate a basic percentage for approval.

On https://beta.distrochooser.de I've deployed the beta branch which changes the display of the result entries a bit. The current working draft looks like following:

![grafik](https://user-images.githubusercontent.com/2878201/209944004-770a92c7-f5ee-43ea-9ff6-3909ced744b4.png)

The issue I see with that after implementing a basic approach is that the rank and user percentage _might_ pull the user from the away from the ranking of the distributions in the list and "obey" the results based on their user approval, which could be misleading.

I _could_ introduce additional metrics, especially about outgoing distribution clicks to identify result entries which "really" resulted in a user interested in the distribution.

**Comment by cmllr** [comment]
I found out that WikiData offers  many entries about LInux Distributions. This will be used to provide more metrics, such as:

- Desktops
- Package Management
- Distribution Age 
- Licensing models
- Supported processor architectures
- Current version

**Comment by cmllr** [comment]
hey @jamesnoahr!

thanks for the ideas! Currently, I am working on adding WikiData information to the distribution data as a first data source.

Regarding Distrowatch data: I did not manage to find any information about the license of the Distrowatch data. Have you seen information about this? This is the important question here in my opinion rather than the data import itself.

The other sources need further research how to get them in a comparable state, currently I don't see a mode where it can support the decision finding rather than just to be displayed.
