### ISSUE TITLE
[Suggestion] distrochooser with remote-storage

### ISSUE THREAD

**Issue by ghost** [distrochooser/distrochooser#203]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like remote storage support in distrochooser. So that I have a copy of the answers and questions for better privacy and security as a distrochooser user.

#### 1.1 img 1
![image](https://user-images.githubusercontent.com/111701513/209555465-c2effe9e-f730-41a7-b933-fad26ff1becf.png)

**image-description:** As we can see in this image and prototype screen, we have a button called remote-storage. 

#### 1.2 img 2
![image](https://user-images.githubusercontent.com/111701513/209561305-ec68ad8e-2e48-437d-8de6-8e2193aa3575.png)

**image-description:** As we can see in this image and prototype screen, we have a button called remote-storage. By clicking on it, the user can share the information on google drive, dropbox or locally if the remote-storage protocol is installed on his machine.

**Describe alternatives you've considered**
- "Distrochooser is a self-hosted and unhosted program". The remote-storage protocol serves to store any user information usually in self-hosted, unhosted software. 
- Users have a copy of the data from the answers they have marked in distrochooser with network protocol: remote storage *or* 
- Users can download in json/html/xml/yaml/markdown or any format(if there is such option to download data) in distrochooser
- Another advantage of this feature is that I can continue where I left off if for some reason I lose internet access. 
- Remote-storage is an alternative with more secure and privacy to File-Access, WebSQL, local-storage, IndexedDB, cookies or session-storage that saves things(user data) in a session in browser.

**Additional context**
- [self-hosted](https://github.com/awesome-selfhosted/awesome-selfhosted): Services and web applications which can be hosted on your own servers.
- [remotestorage/remotestorage-widget](https://github.com/remotestorage/remotestorage-widget): The code or repository that implements the remote-storage widget.
- [unhosted](https://github.com/0dataapp/awesome-0data): services or web applications where you have 100% control of your data, including choosing who owns your data or not. Also, they are services or applications that work without a database or nobackend.
- [remotestorage](https://remotestorage.io/): network protocol for self-hosted and unhosted applications. The advantage of using the remote-storage protocol is that it works offline, the user has his own data, it is synchronizable and has good compatibility - compared to other network protocols.

**Comment by cmllr** [comment]
hey, thank you for the suggestion, but what exactly do you mean with that? Especially the "privacy" confuses me a bit as Distrochooser is designed privacy-friendly, no personal data is collected and each result is stored anonymously. 

A thing what *could* be an idea to offer a downloadable result (in a defined format) - do you mean something like that?

**Comment by cmllr** [comment]
okay, I will take a look on this and will update this thread.

**Comment by cmllr** [comment]
I still don't understand how using this approach has any benefit for the user rather than just storing the results in a database and giving out a link with an ID?

**Comment by cmllr** [comment]
The ID is links to an anonymous result, so there is no mapping possible between a given User and a given result. So the GDPR (in my opinion) does not apply here, also as Distrochooser does no logging. Even if a user want's a GDPR data export I would not have any option to map a given user/ client to a result.

> In my view, linux communities and distrochooser are storage providers.

I kind of agree, but I never saw any major service to adopt this service/ protocol/ approach. I am afraid implementing this would lead to a less used feature causing additional maintenance effort. You need to keep in mind that such an feature needs maintenance, too.

> Or... If I want I can sync my data only with google drive and dropbox - or not too (but... If I need to make my data public, I could use things like orbit-db too)

This basically sounds like you could achieve the same with just offering an (JSON) dump of your given answers and an import textbox.

>As you can see, the decision where the data goes is up to the user, not the community or open source tool.

Yes, but I would totally agree when we would be talking about GDPR-related data here. But we are here only talking about anonymous data of the given answer of the questionnaire.

It is hard for me to imagine a use-case where the implementation of remote-storage (or similar) would result in a wide used feature with a large benefit than it's implementation or maintenance.

**Comment by cmllr** [comment]
Thanks for the discussion, but I am closing this for now as I don't really see the benefit of this _for the moment_. It might become relevant somewhere in the far future, but not for the near future.
