### ISSUE TITLE
Provide clickable links to the distribution's website

### ISSUE THREAD

**Issue by xahodo** [distrochooser/distrochooser#210]
Wouldn't it be nice if, after people have completed the questionnaire and their list of distributions is displayed, they would be able to click on one of the distribution's images in order to go to the distribution's website, so they can obtain more information or can immediately download it?

[NOTE]Was not able to check whether this issue is actually implemented, as distrochooser seems to be inaccessible for me at the moment.

**Comment by cmllr** [comment]
![image](https://user-images.githubusercontent.com/2878201/209552640-66830a50-1d46-4693-bebb-14e7d3f7cdfd.png)

Hey, thanks for the remark! Each distribution has a "distribution homepage" link referring to the main website of the distribution. I stepped away from adding images as discussed in #148, so each result entry is text-only.

The server outage was resolved in the meantime and I am now monitoring the infrastructure.
