### ISSUE TITLE
[Suggestion] distrochooser with version bot

### ISSUE THREAD

**Issue by codehangen** [distrochooser/distrochooser#211]
**Is your feature request related to a problem? Please describe.**
This request is related to the issue: "metrics in distrochooser" in [[Suggestion] metrics for distrochooser](https://github.com/distrochooser/distrochooser/issues/200) and issue: "prefer mainstream distributions over the smaller ones" in [[Suggestion] Prefer mainstream distributions over the smaller ones](https://github.com/distrochooser/distrochooser/issues/193)

**Describe the solution you'd like**
I would like a bot version of distrochooser for these reasons:
1. platform independence: I wouldn't need to access the site (I could access any linux community which I participate and use distrochooser bot to answer doubts as a beginner, advanced or intermediate user).
2. automation: a bot allows you to automate certain things and this is useful in most cases for manual tasks, some linux community might be interested in distrochooser with automation to check the type of user: advanced, beginner, intermediate and forward this type of user to some helpdesk area, user guide, documentation, etc or no.
3. support: maybe... there would be support from all linux communities with distrochooser-bot whether for user experience research or even for ui, design research etc.
    - *Unlike the case of automation, if distrochooser is a great tool, we can support many linux communities, which includes support for automation, not just the automation process*
5. distribution: maybe... there would be many channels where distrochooser-bot is supported or can support. *distrochooser-bot could help clarify doubts with chat, email, forum linux etc.*
6. decentralized management: I believe that distrochooser can be used by any company, linux community to improve the linux experience in a decentralized way - *you can ask questions about software licensing in your community, and other questions for advanced users, beginners.*
7. "AI(Artificial intelligence)": distrochooser-bot can search any pages on the internet to improve user interaction with the linux distro. or in another case, distrochooser-bot can be used by anyone to improve the linux experience
8. metrics: it is possible to have metrics in distrochooser with bot by transfer or store data or user interation

**Describe alternatives you've considered**
1. You could use distrochooser-bot on protocols like XAMPP/Solid-Project/Matrix/Email etc. In this sense, we can have a distrochooser-bot version for each network protocol or
2. We can use protocols like matrix that offers the feature of bridges, it is possible with bridges to forward messages from the matrix to other client messages such as twitter, telegram, whatsapp, instagram, discourse, discord or any forum etc.

**Additional context**
- bot: "an autonomous program on the internet or another network that can interact with systems or users."

**Comment by cmllr** [comment]
Based on available time, this can't be done. Additionally, there are _alot_ of possible platforms this requires to cover. Based on the current user/platform distribution, I would prefer focusing on the Web version and implement an additional platform/program-interface (like a bot) if there is a _specific_ need for it.

**Comment by bestprogrammerworld** [comment]
> Currently there are things like chat gpt(Optimizing Language Models for Dialogue - OpenAI) - which has some automation with artificial intelligence. But that must be thought of before anything else. Bear in mind that it may not conform to what is already standard in this open source project.

There are free bots for email, issues, pull-requests all of that with the matrix network protocol: `https://t2bot.io/`

My question is the following: why can't we use bots to automate questions, pull-requets, discussions ?
