### ISSUE TITLE
 [Suggestion] apis in distrochooser

### ISSUE THREAD

**Issue by codehangen** [distrochooser/distrochooser#212]
**Is your feature request related to a problem? Please describe.**
This request is related to the issue: "metrics in distrochooser" in [[Suggestion] metrics for distrochooser](https://github.com/distrochooser/distrochooser/issues/200) and issue: "prefer mainstream distributions over the smaller ones" in [[Suggestion] Prefer mainstream distributions over the smaller ones](https://github.com/distrochooser/distrochooser/issues/193)

**Describe the solution you'd like**
*So... I will comment on every feedback I received - and "the solution" I considered here.*

**Describe alternatives you've considered**

*message, feedback*
> The problem with the statistics from distrowatch is that they measure clicks, i.e. how many people went to the website of a particular distribution, not actual installs.
> A more accurate measurement (with conservative room for error) is to check how many people participate in their communities (lots of work, I know, but it's the better metric). You could check things like irc/matrix logs (for the amount of discussion for the last several days), forums (you could ask the forum admin to do a query on the database for the amount and frequency of user activity in the same amount of time), and reddit (where you just check how many posts there are in their subreddits for the last while).
> LOTS of work, but it's bound to give more accurate information then just clicks.

#### 1. problem
> The problem with the statistics from distrowatch is that they measure clicks, i.e. how many people went to the website of a particular distribution, not actual installs.

#### 1.1 answer and concept
I initially talked about having a metric based on GitHub, GitLab, Discourse, Bitbucket, Source-hut and other places, including Distrowatch. That is, I call this process multi-metric (multiple associated metrics), this avoids any repeated or erroneous data in quantitative terms by having multiple data with or without api in distrochooser... because... In that sense, there would be a quantitative margin for error.

#### 2. problem
> A more accurate measurement (with conservative room for error) is to check how many people participate in their communities (lots of work, I know, but it's the better metric). You could check things like irc/matrix logs (for the amount of discussion for the last several days), forums (you could ask the forum admin to do a query on the database for the amount and frequency of user activity in the same amount of time), and reddit (where you just check how many posts there are in their subreddits for the last while).

#### 2.1 answer and concept
Great idea. *So... for example, there is the [discourse-api](https://github.com/discourse/discourse_api) api, most of the linux community uses it: [Discourse](https://www.discourse.org/) as Manjaro, Fedora, Ubuntu etc.*  So... If distrochooser add [discourse-api](https://github.com/discourse/discourse_api) - we could evaluate how many users there or are for each linux distro.  But... we need more api in distrochooser publicly, privately or anonymously too.

#### 3. problem
> LOTS of work, but it's bound to give more accurate information then just clicks.

#### 3.1 answer and concept
Well I imagine that the general issue is the integration with various public, private or anonymous APIs to analyze a multimetric and associative measure. If distrochooser is a highly rated project, perhaps every and every linux distro can sends an api for us to publicly and anonymously query the real linux user base (because... "for me this question refers to the idea of open data", knowing the real amount of linux users is an open data question, it does not involve privacy or data security, it is a real thing for the community.... to improve ui/ux in linux or distro-linux).

**Additional context**
- [api](https://www.ibm.com/topics/api): "An API is a set of defined rules that explain how computers or applications communicate with one another." 
- I used screen prototypes, I did more scientific, academic research.
- I hope to clarify or help in some way
- I am sending this new feedback to get new feedback as well.

**Comment by cmllr** [comment]
I think a general approach for this would be to contact the distribution teams and to ask for available data sources - and make a decision on this after that information was received.

At the end you'll need to have an approval that you can use this data. Otherwise this could lead to legal/ privacy implications. I will mark that as an open todo for now as this is more a process issue than an implementation question.

**Comment by cmllr** [comment]
Additionally: An idea would be to use publicly available data, such as https://www.wikidata.org/wiki/Q7715973

**Comment by cmllr** [comment]
I will close this issue in favor of #200 as this has a quite large overlap with it, we can continue the discussion on that issue.
