### ISSUE TITLE
[Suggestion] Generate user profile in distrochooser

### ISSUE THREAD

**Issue by codehangen** [distrochooser/distrochooser#216]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like to have as a final result an evaluative profile of how I am as a linux user.

**Describe alternatives you've considered**
![image](https://user-images.githubusercontent.com/111701513/210039243-a1ec80a2-6c6a-41ad-8e28-9fe433da85b4.png)

**image-description:** As we can see in the image, distrochooser generates the user profile and the corresponding linux distro.

**Additional context**
No.

**Comment by cmllr** [comment]
Thanks for the idea, I see a bit of a problem here as the user answers need to be transformed into an numeric value. This value needs to rely on a scale to be plotted. 

If that _would_ be resolved I don't think that the user benefits from this as the focus of the results should rely on the distribution result, not a user profile, at least for the current approach.
