### ISSUE TITLE
[Suggestion] Filter search results in distrochooser

### ISSUE THREAD

**Issue by ghost** [distrochooser/distrochooser#217]
**Is your feature request related to a problem? Please describe.**
This request is related to the issue: "metrics in distrochooser" in [[Suggestion] metrics for distrochooser](https://github.com/distrochooser/distrochooser/issues/200) and issue: "prefer mainstream distributions over the smaller ones" in [[Suggestion] Prefer mainstream distributions over the smaller ones](https://github.com/distrochooser/distrochooser/issues/193) and issue: "limit number of distro's shown in results by default" in [Limit number of distro's shown in results by default](https://github.com/distrochooser/distrochooser/issues/150)

**Describe the solution you'd like**
I believe this can be solved by adding options based on graphs, apis, open data or even search filters.

#### 1.1 idea 1 or
![image](https://user-images.githubusercontent.com/111701513/210040610-2b50cc15-858e-4201-8de5-57684d7f9aa8.png)

#### 1.2 idea 2 or
![image](https://user-images.githubusercontent.com/111701513/210041709-ce693a85-721a-4742-9a0e-00ee39ea72df.png)

#### 1.3 idea 3
![image](https://user-images.githubusercontent.com/111701513/210042009-c5ea1586-a304-4b2d-a57b-4d484faea2f2.png)

#### 2. Filters
1. **select linux distro by linux distro amount based on development time**: So... Instead of asking for the user's age, it could only ask for linux development time. With that, you could select more or less popular distro... according to the development time compared to other previous distros.
2. **select linux distro by linux distro amount based on x amount of forks available**: Ask if the distro is based on another distro. Generally popular distros are based on popular distros. It's a way to solve this problem here.
3. **select linux distro by linux distro amount based on x amount of languages available**: the more the distro supports the language, the more it will stand out against other linux distros that do not support one or more languages, dialects.
4. **select linux distro by linux distro amount based on x amount of available companies that use or support linux distro**: another complementary idea would be that you can check if the distro is more or less popular if the distro is compatible with popular drivers from companies like Dell, Apple etc in terms of driver for audio, video, wifi or any technical information like that. For example, if the distro has macbook compatibility and it works. Or does it only work with Dell drivers etc. This can be more or less useful for the user. 
5. **select linux distro by linux distro amount based on locale:** Another interesting option is to select the distro where it was developed, such as Brazil, United States, etc. A Linux distro can be more or less popular based on the x amount of distros produced by the country, state, city or region, municipality.
6. **select linux distro by x amount of download**
7. **select linux distro by amount of available hardware**
8. **select the linux distro by any company of your choice**
9. **select the linux distro through technical question**
10. **select the linux distro with public, private or anonymous metrics or with the api available or not**
11. **select linux distro by x amount of clicks**
12. **select the linux distro through a bot**
13. **select the linux distro through a crawler**

**Describe alternatives you've considered**
- [Choices-js](https://choices-js.github.io/Choices/): "Choices.js is a lightweight, configurable select box/text input plugin. Similar to Select2 and Selectize but without the jQuery dependency."
- [mdbassit.github.io/FancySelect/demo](https://mdbassit.github.io/FancySelect/demo.html): "fancySelect"

> I think a general approach for this would be to contact the distribution teams and to ask for available data sources - and make a decision on this after that information was received.
> At the end you'll need to have an approval that you can use this data. Otherwise this could lead to legal/ privacy implications. I will mark that as an open todo for now as this is more a process issue than an implementation question.

1. I recently wrote an issue here: [[Suggestion] apis in distrochooser](https://github.com/distrochooser/distrochooser/issues/212) - I talked about the idea of ​​what I conceptually called a multi-metric process (multiple associated metrics. Part of this idea can be used by adopting search filters or search filter engines.
2. One of the most important factors in this process is making user types and data types. Think what type of data and type of user are "sources". For example, we may have questions ignored by a more or less experienced user. And we can have a data source associated with that.

*conceptual and mathematical example*
![image](https://user-images.githubusercontent.com/111701513/212811305-d140b3c1-d5cb-4004-bbe2-a5c4fccad625.png)

**img-description:** As we can see in the image, people can choose the ubuntu distro for reasons of indication, previous experience, general knowledge, license, ease of use, etc. This picture in general terms is nothing more than a Veen-Euler diagram, something in set theory. Each person can be in one or more sets depending on the answer and the question.

*The idea of a search filter is something like implementing a veen-euler diagram.*

**Additional context**
None.

**Comment by cmllr** [comment]
Hey, thank you for your suggestions here and in #219. Just to inform: I am currently working on an approach to show the user strenghts and weaknesses of the distribution by an image similiar to the one you displayed here and on https://user-images.githubusercontent.com/111701513/211167452-3503ab96-6e47-43cf-a617-492474e53009.png.

**Comment by cmllr** [comment]
Thanks for the idea @jamesnoahr, I think I will take a look at chart.js as I think there is a Vue.js wrapper available (as distrochooser uses Vue in the frontend)

**Comment by laoen** [comment]
```graphql
query {
  apiDistrochooser {
       memory ram, 
       discourse, 
       hardware, 
       package, 
       language, 
       crawler, 
       wikipedia,
       user profile, 
       license, 
       support
  }
}
```
