### ISSUE TITLE
[Suggestion] Idle Detection API in distrochooser

### ISSUE THREAD

**Issue by codehangen** [distrochooser/distrochooser#218]
**Is your feature request related to a problem? Please describe.**
None.

**Describe the solution you'd like**
The Idle Detection API provides a means to detect the user's idle status, active, idle, and locked, specifically, and to be notified of changes to idle status without polling from a script.

I would like to be notified if I stop answering questions.

*example Idle Detection API in distrochooser*
![image](https://user-images.githubusercontent.com/111701513/211125555-fa5e0241-240b-4d75-b464-cf4b5f54a72d.png)

**Describe alternatives you've considered**
- case 1: if the user takes too long to answer, skip to the next question or no.
- case 2: we can skip question if user is idle or no.
- case 3: prevent user from forgetting to answer something or skipping the answer by accident or no.
- case 4: I would like to be notified if I stop answering questions.
- case 5(privacy): Some people say that for the sake of privacy it's better to leave the idle option disabled, which can hinder the implementation of this feature.

**Additional context**
[Idle_Detection_API](https://developer.mozilla.org/en-US/docs/Web/API/Idle_Detection_API): "The Idle Detection API provides a means to detect the user's idle status, active, idle, and locked, specifically, and to be notified of changes to idle status without polling from a script."

**Comment by cmllr** [comment]
Thanks for the idea. Based from the number I have, I don't think such an feature is required as the mean stay time is around 200 seconds. I don't think that many users idle while using the service.
