### ISSUE TITLE
[Suggestion] choose questions about linux distro according to behavioral profile

### ISSUE THREAD

**Issue by ghost** [distrochooser/distrochooser#219]
**Is your feature request related to a problem? Please describe.**
This request is related to the issue: "prefer mainstream distributions over the smaller ones" in [[Suggestion] Prefer mainstream distributions over the smaller ones](https://github.com/distrochooser/distrochooser/issues/193), issue: "filter search results in distrochooser" in [Filter search results in distrochooser](https://github.com/distrochooser/distrochooser/issues/217), issue: "metrics for distrochooser" in [[Suggestion] metrics for distrochooser](https://github.com/distrochooser/distrochooser/issues/200), issue: "distrochooser is the solution for distrohopping?" in [[Suggestion] distrochooser is the solution for distrohopping?](https://github.com/distrochooser/distrochooser/issues/196), issue: "Software availability and a way to rank what is more important to the user" in [Software availability and a way to rank what is more important to the user](https://github.com/distrochooser/distrochooser/issues/138), issue: "limit number of distro's shown in results by default" in [Limit number of distro's shown in results by default](https://github.com/distrochooser/distrochooser/issues/150), issue: "user experience section - an option to pick your favorite distro as a consumption" in [[Suggestion] User experience section - An option to pick your favorite distro as a consumption need](https://github.com/distrochooser/distrochooser/issues/194), issue: "why are some advanced distributions included?" in [Why are some advanced distributions included?](https://github.com/distrochooser/distrochooser/discussions/223) and issue: "change the questions depending on if they are (linux) beginnner" in [Change the questions depending on if they are (linux) beginnner](https://github.com/distrochooser/distrochooser/issues/149)

**Describe the solution you'd like**
1. I would like to skip basic and technical questions based on time, for example if I have a time of 15 seconds then distrochooser questions can be skipped.
2. Another thing I would like.... have questions on "behavior, quality, management,organization or productivity in distrolinux" - with these questions I could decide which linux to choose.
3. Many companies evaluate employees by behavioral profile and technical skills. I believe that we can evaluate users according to a behavioral, technical profile in distrochooser.
4. Many times, those using distrochooser do not know the technical term, it is better to skip certain questions automatically based on a time or user priority.
5. Choosing a distro linux or operating system is always a matter of convenience and priority. The topic that opens here discusses this idea in a clearer, more objective way possible through administration tools, management as a priority matrix eisenhowser, swot, talentoday.
6. Based on these questions in the swot/eisenhower matrix or talentoday, it is possible to rank a linux distro more or less popular - Therefore, including subsequent search results may be small with based on these questions in the swot/eisenhower matrix or talentoday too.

**Describe alternatives you've considered**
- **img 1. distrochooser and talentoday(idea)**
An interesting and random idea I had was to ask behavioral questions to base the choice of linux distro. Behavioral questions are very common to assess certain professional skills or soft-skills in the workplace. But one thing I noticed, is that we can evaluate the linux distro by the user's behavioral profile.

<img src="https://user-images.githubusercontent.com/111701513/211167354-9cca8213-54b2-4eab-8d34-92b00bcd80d9.png" width="500px"/>

**image-description:** Image credit goes to talentoday, the image was taken from the homepage of the site talentday. After answering a series of questions, the user knows a little about himself. The talentoday tool is based on questions according to psychology - that's what it says on the official website. Many companies use talentoday to improve employee hiring, it is not a final step, but an initial one.

**img 1.1 distrochooser and talentoday(concept)**
<img src="https://user-images.githubusercontent.com/111701513/211167452-3503ab96-6e47-43cf-a617-492474e53009.png" width="500px"/>

**image-description:** *As we can see in this conceptual image we have a graph that demonstrates the type of user and the profile of the linux distro.*

- **img 2. distrochooser and SWOT Analysis(idea)**
<img src="https://user-images.githubusercontent.com/111701513/211166075-d0170149-3c27-4777-a778-5f0fdae111bd.png" alt="image" width="400px"/>

**image-description:** *Questions: "this question is hard to answer", "this question is easy to answer", "I don't want to answer this question", "I don't have the knowledge to answer this question" - may be related to the swot matrix that I mentioned earlier.

**img 2.1 distrochooser and SWOT Analysis(concept)**
![image](https://user-images.githubusercontent.com/111701513/211167046-fad46a54-b22d-4a6c-ae0a-ea8576a884ef.png)

**image-description:** *The user can mark the questions according to his interests. Something I thought initially would be to use the swot matrix to check this possibility.*

- **img 3. eisenhower matrix(idea)**
<img src="https://user-images.githubusercontent.com/111701513/211165077-6fff2a9e-fdbf-4404-9420-a4f14e411f79.png" alt="image" width="700px"/>

**img 3.1 distrochooser with einsenhower matrix 1(concept)**
<img src="https://user-images.githubusercontent.com/111701513/211165451-3edfda12-faba-4c05-b41e-2e6dfca81f3c.png" alt="image" width="700px"/>

**image-description:** Questions like: "this question is not important", "this question is urgent", "this question is neither urgent nor important", "this question I will answer later". *Depending on the user's answer, new questions can be ignored based on the behavior of what is: "important", "urgent", "not important and not urgent" or what is "to be answered later" based on the eisenhower matrix.*

**img 3.2 distrochooser with einsenhower matrix 2(concept)**
![image](https://user-images.githubusercontent.com/111701513/211167075-729b2aa1-b048-4bed-8942-3f0de5bcfe94.png)

**image-description:** *an interesting idea is tagging questions.*

**img 3.3 distrochooser with einsenhower matrix 3(end-concept)**
![image](https://user-images.githubusercontent.com/111701513/211165834-66f68294-e5c3-4867-b593-5e256b94c89c.png)

**image-description:** *Before offering any option to be answered through a basic or technical question, we offer the user an option if the question makes sense to him based on the eisenhower priority matrix.*

- **img 4. distrochooser with time-quiz(idea)**
<img src="https://user-images.githubusercontent.com/111701513/211167667-c6571ef4-81fe-45bd-a104-43e37d22efbc.png" width="450px"/>

**img 4.1 distrochooser with time-quiz(concept)**
<img src="https://user-images.githubusercontent.com/111701513/211167772-0539b9e3-2d18-4ec9-a3dd-b80de1345d62.png" width="450px"/>

**img 4.2 distrochooser with time-quiz(end-concept)**
<img src="https://user-images.githubusercontent.com/111701513/211167889-65acfdd6-b481-44cc-9881-676cf0ee55c1.png" width="550px"/>

**image-description:** *Basic, advanced, technical questions are ignored if the user does not have time to fill them out.*

**img 5. We can rate the question or answer type with a value between 1 to 10.**
![image](https://user-images.githubusercontent.com/111701513/211175640-7f382e50-08ac-4492-b8c7-3da8d3c01ee7.png)

**img-description:** The user can add a numerical scale for the perceived effort in answering this question if the checkbox option is not used.

**img 6. my idea: ask questions about linux distro according to behavioral profile 1**
![image](https://user-images.githubusercontent.com/111701513/211168067-66496bb3-3cd0-41c3-af42-1f2d2565fc30.png)

**image-description:** *Here in this image we have time to answer the questions along with the priority matrix: einsenhower.*

**img 7. choose questions about linux distro according to behavioral profile 2** 
![](https://raw.githubusercontent.com/codehangen/QuizKNN/master/example.gif)

**image-description:** As we can see in this image in gif format, we can use the camera to move questions and answers in distrochooser in case we identify the movement of the hands. Please, see this [QuizKNN](https://gabrieltavernini.github.io/QuizKNN/). I didn't create the source code, but we can use it if you find it interesting in this use case.

**Additional context**

- [Talentoday](https://www.talentoday.com/): "People Analytics & Soft Skills Testing Software. Talentoday provides science-driven people analytics to fuel better decision making at all points of the employment life cycle."
- Also known as SWOT Analysis, it consists of an in-depth and detailed analysis of a macro scenario that will help you make decisions. Beforehand, the acronym is a term in English, which refers to a set of four words: Strengths, Weaknesses, Opportunities and Threats.
- quiz with time: please, see this source code [codepen-io/harunpehlivan/full/bGeOPye](https://codepen.io/harunpehlivan/full/bGeOPye)

**Comment by cmllr** [comment]
Hello everyone,

I don't see why there should be such an major change in the decision making. There are many ideas currently in the room which really improve the decision finding without making the questionnaire itself more complicated. Especially more straightforward filtering/ more criteria to filter on (e. g. #220  or #217)

@jamesnoahr currently, there is no need to use a captcha service. The results caused by bots are currently (more or less) identifiable, so I don't think a captcha like service is needed here. Also, I cannot embed any captcha third party service as this would have major implication on the privacy of the user, which is not to desire.
