### ISSUE TITLE
JSONForm with distrochooser

### ISSUE THREAD

**Issue by ghost** [distrochooser/distrochooser#226]
**Is your feature request related to a problem? Please describe.**
None.

**Describe the solution you'd like**
I would like distrochooser to be structured in [JSON Form](https://github.com/jsonform/jsonform/wiki).

![](https://i.imgur.com/M8ZCES5.gif)

**Describe alternatives you've considered**
- According to the project description distrochooser. distrochooser is "an orientation guide for Linux newbies". In this sense, we can have a file format structure compatible with the description and purpose of the project. [JSON Form](https://jsonforms.io/examples/basic) is an interesting format for questions and answers, for quizzes and for such an interesting tool as distrochooser. It is very easy with the JSONForm file format to logically structure certain inputs and outputs.
- There are libraries in vuejs, react-js that support the JSON Form file format. This would make it easy to create question and answer based user interface screens, like: react-jsonschema-form  etc.

*vision*
![image](https://user-images.githubusercontent.com/123137817/218148553-4e16d9ee-0762-4962-ad88-7b6bdedfcf40.png)

*JSONSchema.json*
```json
{
  "title": "Some distributions are made for a special purpose, some for daily use. What do you need?",
  "description": "",
  "definitions": {
  },
  "type": "object",
  "properties": {
    "multipleChoicesList": {
      "type": "array",
      "title": "You may choose multiple answers",
      "items": {
        "type": "string",
        "enum": [
          "I want a distribution for daily use",
          "I want to use Linux for anonymous web browsing",
          "I prefer a distribution which is supported by game publishers",
          "I want to execute all programs in an isolated area",
          "The user is visually impaired",
          "Has Live Mode: Can be started using discs or usb sticks to test it out (before installing)"
        ]
      },
      "uniqueItems": true
    }
  }
}
```

*UISchema.json*
```json
{
  "multipleChoicesList": {
    "ui:autofocus": true,
    "ui:emptyValue": "",
    "ui:widget": "checkboxes",
    "ui:autocomplete": "family-name",
    "ui:options": {
      "orderable": true
    }
  }
}
```

*formData.json*
```json
{
  "multipleChoicesList": [
    "Has Live Mode: Can be started using discs or usb sticks to test it out (before installing)"
  ]
}
```

**Additional context**
- [react-jsonschema-form](https://rjsf-team.github.io/react-jsonschema-form/docs/) is a simple React component capable of building HTML forms out of a JSON schema.
- [JSON Schema](https://json-schema.org/) is a declarative language that allows you to annotate and validate JSON documents. JSON Schema enables the confident and reliable use of the JSON data format.
- JSON Form library is a JavaScript client-side library that takes a structured data model defined using [JSON Schema](http://json-schema.org/) as input and returns a [Bootstrap](http://twitter.github.com/bootstrap/)-friendly HTML form that matches the schema. The layout of the generated HTML form may be entirely fine-tuned through a simple declarative mechanism.

**Comment by cmllr** [comment]
Thank you for this suggestion, but I currently don't see why I should rework the questionnaire just to use a framework? Additionally, the questions are not delivered from any file structures, so there would be the need to rework that aswell. 

Could you please specify why you think this would be an alternative? Thank you!
