### ISSUE TITLE
[suggestion] Package compilation Criteria

### ISSUE THREAD

**Issue by Rathmox** [distrochooser/distrochooser#228]
**Is your feature request related to a problem? Please describe.**
I searched for some and Gentoo came as second place, and I really don't want it because I don't want to compile packages

**Describe the solution you'd like**
Add a Package compilation criteria that can be checked as an option

**Additional context**
Compilation based distros examples:
Gentoo
Funtoo

**Comment by cmllr** [comment]
hey @Rathmox, thanks for the report!

I know that there are some advanced distributions in the list, but I think at the moment this is not achievable and would lead to more confusion of the user (same counts for the "I don't want systemd" answer which is also slightly misplaced in the current version). 

I think at a later point your remark can be included with the implementation of  #149 (which is still in the far far future). I will close this for now, as there will be a decision matrix overhaul required, including the mentioned aspect you reported on also.
