### ISSUE TITLE
add logo distro 

### ISSUE THREAD

**Issue by eantho** [distrochooser/distrochooser#233]
**Is your feature request related to a problem? Please describe.**
The distrochooser displays results from the linux distro without a logo, which I think is a bad design principle.  In my view the user must have a linux recognition according to the logo of the community where linux is developed.

**Describe the solution you'd like**
A general idea is to add the html semantic tag `<img src=""/>`

**Describe alternatives you've considered**
***before***
![image](https://user-images.githubusercontent.com/125943841/220557975-f1709bd7-2211-4faf-80ce-b5494688716e.png)

*vs*

***after***
![image](https://user-images.githubusercontent.com/125943841/220559302-a0670723-347d-47b8-8c34-f00139d8f137.png)

**Additional context**
None.

**Comment by cmllr** [comment]
Hey, thanks for the suggestion, but I decided to not include distro logos in the result. A full discussion about that topic can be seen on #148
