### ISSUE TITLE
choose the linux or linux distro by the graphical interface or not of the installation

### ISSUE THREAD

**Issue by eantho** [distrochooser/distrochooser#234]
**Is your feature request related to a problem? Please describe.**
I got this idea based on the discussion: [(question) distrochooser version: desktop installer?](https://github.com/distrochooser/distrochooser/discussions/215), [Why are some advanced distributions included?](https://github.com/distrochooser/distrochooser/discussions/223). This idea is similar to the issue: [[Suggestion] User experience section - An option to pick your favorite DE #192](https://github.com/distrochooser/distrochooser/issues/192), [adding a distro for administrators](https://github.com/distrochooser/distrochooser/issues/161)

**Describe the solution you'd like**
We could ask if the user prefers to install a linux or linux distro through [calamares](), [buildroot](https://buildroot.org/) or [yoctoproject](https://www.yoctoproject.org/), anaconda-installer, personal-distro-configurator, shell-installer, linux-installer, [Ubiquity](https://github.com/linuxmint/ubiquity), [linux-gui-installer](https://github.com/grandchild/linux_installer) or guides as [try-linux](https://evanwill.github.io/try-linux/) etc. And it displays an image where he chooses the installation's graphical interface, in that sense, if he chooses buildroot, he wants a customized installation. 

***Examples***

***calamares installer***

<img src="https://user-images.githubusercontent.com/125943841/220686946-32dd4fb3-ea8b-4d6c-891d-9f727f7fa269.png" alt="image" width="500px"/>

*vs*

***buildroot  installer***

<img src="https://user-images.githubusercontent.com/125943841/220687311-d3829d0b-9284-48ba-b81d-b87c7a37f05e.png" alt="image" width="500px"/>

*vs*

***ubuntu-installer***

<img src="https://user-images.githubusercontent.com/125943841/220687411-74e59fba-c8a5-4941-b021-8bf4c8da864d.png" alt="image" width="500px"/>

***sheeplinux-installer***

<img src="https://user-images.githubusercontent.com/125943841/220687606-2395c08f-3203-469c-9075-8d3818f94190.png" alt="image" width="500px"/>

**Describe alternatives you've considered**
An idea: we can ask the user how he prefers to install the linux distribution or install linux. We can have a slideshow, showing installation interfaces. If he chooses some graphical interface or not for installation, a distro or another distro must be displayed at the end compatible with the previous choice.

**Additional context**
None.

**Comment by cmllr** [comment]
thanks for the suggestion. I think this is out of scope. Distrochooser is, at least for the moment, an orientation tool and not an in-depth selection helper (which would only achievable with a proper set of data sources, which is not yet available).
