### ISSUE TITLE
[bug-fix]: "terms, words of distrochooser tool"

### ISSUE THREAD

**Issue by ghost** [distrochooser/distrochooser#235]
**Is your feature request related to a problem? Please describe.**
None.

**Describe the solution you'd like**
Correction of terms, words of distrochooser tool.

**Describe alternatives you've considered**

*before*
> Distrochooser.de Logo
> Welcome!
> Software: Use case
> Computer knowledge
> Linux and you
> Installation: Presets
> Hardware support
> Source for help
> User experience
> Distributions: Price
> Distributions: Scope
> Distributions: Ideology
> Distributions: Privacy
> Administration
> Software: Updates

***img-before***
![image](https://user-images.githubusercontent.com/125943841/220696485-6ee239c5-a426-447a-9c1e-16be7a236f66.png)

*after*
> Distrochooser.de Logo
> Welcome!
> Use case
> Computer knowledge
> Community
> Installation: Presets
> Computer support
> Knowledge base
> User experience
> Pay assistance/technical support
> Purpose
> General Proposal
> Privacy
> Administration
> Updates

**Additional context**
None.

**Comment by xahodo** [comment]
I'd also like to suggest to change from "hardware support" to "computer support", to make things clearer. The newbie might not know what the term "hardware" means.

**Comment by cmllr** [comment]
Thank you two for the suggestions, 

to summarize/ give feedback:

|old|new|my remarks/ approval|
|--|--|--|
|Software: Use case|Use case| ok|
|Linux and you|Community|Overlaps in my opinion to much with the old "Source for help" question content. Also the question has nothing to do with communities, it is only related to the users linux knowledge|
|Hardware support|Computer support|ok|
|Source for help|Knowledge base|See remarks for "linux and you/community"|
|Distributions: Price|Pay assistance/technical support|Too long. Also "pay assistance" is a bit hard to understand as this flag also contains distribution mappings for distributions not offering a support subscription and instead you purchase a release|
|Distributions: Scope|Purpose|The scope question defines a scope, not a purpose|
|Distributions: Ideology|General Proposal| Don't know yet (I am not a native speaker, so I can't really judge this)|
|Distributions: Privacy|Privacy|ok|
|Software: Updates|Update|ok|

**Comment by cmllr** [comment]
> Hi.
> 
> > Thank you two for the suggestions,
> > to summarize/ give feedback:
> 
> When in doubt, it is better to leave some terms as they are. For example:
> old 	new 	my remarks/ approval
> Software: Use case 	Use case 	ok
> Linux and you 	Linux and you 	ok
> Hardware support 	Computer support 	ok
> Source for help 	Source for help 	ok
> Distributions: Price 	Price 	?
> Distributions: Scope 	Scope 	Scope
> Distributions: Ideology 	General Proposal 	?
> Distributions: Privacy 	Privacy 	ok
> Software: Updates 	Update 	ok

I agree with almost all, but I still think I will stick on the "Ideology" and "price" (but removing the "DIstributions:" prefix). I will add them into the english base translation, but I think it needs some additional work to reflect these change in all other translations. `en`, `de` and `gsw` will directly reflect these changes.

**Comment by cmllr** [comment]
Changes implemented, will update together with the other changes from #220
