### ISSUE TITLE
can distrochooser work offline?

### ISSUE THREAD

**Issue by eantho** [distrochooser/distrochooser#236]
**Is your feature request related to a problem? Please describe.**
None.

**Describe the solution you'd like**
I would like to use distrochooser without internet connection. When you have internet connection, the new survey is sent.

**Describe alternatives you've considered**
- We could create a 100% python interface with tkinter instead of having a frontend technology like vuejs.
- the advantage is that we can distribute this package via Chocolatey/flatpack etc in binary form, where the user installs and uses it.
- the advantage of a 100% python code is its performance, it runs on the user's machine and does not need internet.
- we can create a mini agent to send data when the user installs distrochooser.
- another advantage is that we can know how many people use distrochooser by physically speaking.

**Additional context**
- [nullboard](https://nullboard.io/preview) - works completely offline with (html, css, js) and has a nullboard agent for backup
- [(question) distrochooser version: desktop installer?](https://github.com/distrochooser/distrochooser/discussions/215) - this would only make sense if distrochooser is used offline.
- [[Suggestion] distrochooser with remote-storage](https://github.com/distrochooser/distrochooser/issues/203)

**Comment by cmllr** [comment]
Hey @eantho , thanks for the suggestion.

Currently, I want to focus on one plattform (the web version).
