### ISSUE TITLE
Remove Manjaro Linux from the list of potential choices

### ISSUE THREAD

**Issue by xahodo** [distrochooser/distrochooser#238]
Manjaro has historically had chronic issues, which can be cause of severe issues for the Linux newbie.

A) They're based on Arch Linux, and copy packages from there. However, they hold back said packages for two weeks in order to "guarantee stability", all the while really doing nothing. If the user decides to get packages from the AUR, this can be a real cause for issues.
B) There's a *pattern* of the distribution's management not looking after SSL certificates. They even once had the audacity to suggest setting the system clock back in time to their users, in order to "fix" such an issue with their forums. This issues alone does not exactly speak of a competent management.
C) Its update script doesn't play well with the package manager (pacman), which can cause issues.

[issues with Manjaro](https://manjarno.snorlax.sh/)

All these issues simply make it irresponsible to show this distribution to _newcomers_. If Manjaro can't be trusted to give good advice to users in case of issues hitting the distribution, I would argue that it's simply irresponsible to funnel users into it.

**Comment by cmllr** [comment]
hey @xahodo , thank you for the information regarding Manjaro. I will review this and will take corresponding actions. FYI: This might take a while as I am currently focusing on code changes rather than updates of the matrix.

**Comment by Aman9das** [comment]
Manjaro, despite its shortcomings, should not be dropped from being a potential choice since it is very popular amongst beginners and provides ease of use features and utilities.

I agree with the sentiment that it wouldn't be the best choice for beginners since there have been issues with it in the past. Still it's large user base speaks to the ease of use of the distribution. They would have switched if it was not good.

**Comment by cmllr** [comment]
> Manjaro, despite its shortcomings, should not be dropped from being a potential choice since it is very popular amongst beginners and provides ease of use features and utilities.
> 
> I agree with the sentiment that it wouldn't be the best choice for beginners since there have been issues with it in the past. Still it's large user base speaks to the ease of use of the distribution. They would have switched if it was not good.

I need to agree with this. I think I will keep Manjaro in the list for now. I might add some remarks to the mapping mentioning these issues .
