### ISSUE TITLE
 theme mode: dark, light or custom in distrochooser

### ISSUE THREAD

**Issue by ghost** [distrochooser/distrochooser#240]
**Is your feature request related to a problem? Please describe.**
Some people may have difficulty seeing certain letters, words.

**Describe the solution you'd like**
I think it would make sense to have a light theme and a dark theme or a custom theme. Customizing the theme color or having a dark theme can help some people who are a little trouble reading very bright things.

**Describe alternatives you've considered**
user decides theme mode: dark, light or custom in distrochooser.

#### theme mode
![image](https://user-images.githubusercontent.com/125943841/221387118-4cf763d4-aad1-4692-8447-a26d842da3c5.png)

#### light mode
![image](https://user-images.githubusercontent.com/125943841/221387153-b2ffcdc9-c50a-447d-bac6-dab433ff86e8.png)

#### dark mode
![image](https://user-images.githubusercontent.com/125943841/221387031-28719a7b-6462-41df-bd7b-4bb33a0a5ae3.png)

**Additional context**
- Text/code editors implement theme mode customization feature where you choose dark/light or custom theme.
- [vanillaframework](https://vanillaframework.io/) - we can use the Ubuntu website theme that comes with a custom style guide. Example: `<link rel="stylesheet" href="https://assets.ubuntu.com/v1/vanilla-framework-version-3.11.1.min.css">`

**Comment by cmllr** [comment]
thanks for the issue, I like the idea. Will take a look on this, but will take some time as I'm still focused on the implementation around #220
