### ISSUE TITLE
[suggestion] site monitoring: distrochooser to check if it is active or fell

### ISSUE THREAD

**Issue by villenmarx** [distrochooser/distrochooser#248]
**Is your feature request related to a problem? Please describe.**
I would like to know what I can do if the Distrochooser site falls or is not more active. Some time some user reported that the Distrochooser website fell, stopped working or was no longer active. For some reason, the technical discussion about this was no longer displayed.

**Describe the solution you'd like**
There are open tools that can monitor in real time if the Distrochooser site is working or fell or has stopped working. An initial consideration is to use a tool [upptime-js](https://upptime.js.org/)

**Describe alternatives you've considered**
1. Monitoring of any site is important, because when a site falls or stops or is not active, it directly affects any company, user, developer, community, employee or contributor whether commercial or not. 
2. In addition to affecting or also affecting results or data, users may feel uncomfortable or employees may feel that this is a failure to manage information technology.
3. A good reason to make the site monitoring openly is because it enables regular tests to find out if the site is inactive. And thereby solve possible connection problems or some technical failure responsible for this problem. In addition, it is easy to find out what are the most common errors in the deploy process or what peak hours are, where the site receives many updates or data.
4. But before requesting this feature, I should mention a general problem with using open source tool for monitoring, is that usually the company or open community has to pay for its own infrastructure. Maybe this doesn't make sense, because there would have to be an infrastructure or server to monitor the distrochooser site. And this requires a certain time or financial cost. Which in general is bad, despite being something good like I said.
5. But thinking in another way, if the open source tool to monitor the distrochooser site has to have a certain payment for the very infrastructure that the distrochooser community requires or makes necessary. An closed source tool requires payment for something recurring and has no infrastructure in which the distrochooser community can decide what is interesting or not, or even something that the distrochooser community might be interested in, because in that case there is no control over any data.
6. When describing these two scenarios, it is necessary to evaluate which is the best or which makes more sense to be adopted. Be it an open or closed source tool for distrochooser website monitoring. Or thinking of another alternative, in case this idea doesn't make sense, this idea must be shelved.
7. There is a resilient protocol over any type of drop, the name of this protocol is IPFS. While it doesn't have much general application on a commercial level, there are products or services implemented in IPFS. There would be no need to monitor the distrochooser site if there was a mirror from another address. For example, if the site goes down, it would make sense to have an IPFS version. In this way, the user accesses the distrochooser website at another network address. The general problem with IPFS is that there are few browsers that implement it, as is the case with Brave Browser.
8. The request for this feature may be out of scope

**Additional context**
- upptime-js: GitHub-powered open-source uptime monitor and status page

**Comment by cmllr** [comment]
Thanks for the suggestion!

I've set up  a upptime worfklow on https://github.com/distrochooser/status, which deploys to https://distrochooser.github.io/status/.
