### ISSUE TITLE
add link to distrochooser API documentation

### ISSUE THREAD

**Issue by ghost** [distrochooser/distrochooser#249]
**Is your feature request related to a problem? Please describe.**
api-distrochooser is already written in [swagger](https://github.com/distrochooser/distrochooser/blob/master/doc/swagger.yaml), but there is no custom link about the api documentation in swagger. I can't find the link about the technical documentation about the api. For example, something like: `https://docs.distrochooser.de/api-version/1/stats/`

**Describe the solution you'd like**
I wish there was online documentation on swagger for the distrochooser api. For example, something like: `https://docs.distrochooser.de/api-version/1/stats/`

**Describe alternatives you've considered**
- We can have a custom link like: `https://petstore.swagger.io/`
- Is there any public api so that I can consult other information through an http call through the rest architecture?  Something like repository: [public-apis/public-apis](https://github.com/public-apis/public-apis) has? Example:
  - Query with the get method all the statistics of distrochooser stats: `https://api.distrochooser.de/api-version/1/stats/getAll`
  - Query with the get method all the distros of distrochooser: `https://api.distrochooser.de/api-version/1/distros/getAll`
or `https://docs.distrochooser.de/api-version/1/` ?

**Additional context**
- "Swagger allows you to describe the structure of your APIs so that machines can read them. The ability of APIs to describe their own structure is the root of all awesomeness in Swagger. Why is it so great?" 
- "Well, by reading your API’s structure, we can automatically build beautiful and interactive API documentation." 
- "We can also automatically generate client libraries for your API in many languages and explore other possibilities like automated testing."
- "Swagger does this by asking your API to return a YAML or JSON that contains a detailed description of your entire API."

**Comment by cmllr** [comment]
Thank you for the suggestion!

the swagger usage in Distrochooser needs an rework. I will add it to my to do list.

**Comment by cmllr** [comment]
Covered with https://github.com/distrochooser/distrochooser/blob/main/OPENDATA.md for now.
