### ISSUE TITLE
Feedback mode

### ISSUE THREAD

**Issue by cmllr** [distrochooser/distrochooser#251]
Add a feedback mode. The mode should allow users to add remarks to the Matrix and suggest changes in an easy way.

- [ ] User identification/ sign up
- [x] Display of current matrix mappings
- [x] Suggestion of changes: Move/ Remove/ Add distro to existing mapping
- [x] Suggestion of changes: Add distro to new mapping
- [x] List of suggested changes (with an abstract)
- [ ] Allow user to add a remark
- [ ] Option to up/ downvote suggestions
- [ ] Edit of mapping type (identify when a new mapping is required)
- [ ] List of unmapped distributions
- [ ] Add option to change language in the feedback mode
- [ ] Spawn domains `feedback.distrochooser.de` and `feedback.beta.distrochooser.de`

**Comment by Het4304** [comment]
Hi,i am looking forward to solve the issues

**Comment by cmllr** [comment]
hey @Het4304 thanks for your interesting in contributing here. This approach was opened quite some time ago when I was working on the previous version, but got stuck on the concept stage. If you are interested in providing a contribution here,  I would love to have an in-depth discussion first - I think it would be good to move this into a discussion or use the project discord (linked in the Readme). I will close this issue in any case for now, but we can pick it up after some concept chat!
