### ISSUE TITLE
[suggestion] Custom themes in distrochooser

### ISSUE THREAD

**Issue by ghost** [distrochooser/distrochooser#253]
**Is your feature request related to a problem? Please describe.**
I would like to have custom themes in distrochooser.

**Describe the solution you'd like**
It would be very interesting to have custom distrochooser themes to improve the experience of using the tool. For example,  let's imagine we have 3 types of custom themes: "default", "chat", "desktop installer". Each of these themes has a visual customization and a target audience that might be interested.

custom theme: "default"
As we can see in the "default" custom theme, the default theme is the question and answer theme like a quiz, it is the theme of the site made available to anyone.

![image](https://user-images.githubusercontent.com/127464474/224496789-5233b85d-017c-4846-9ce9-36c462f434fc.png)

custom theme: "desktop installer"
As we can see in the "desktop installer" custom theme, the question tabs appear in a step-by-step sequence.
![image](https://user-images.githubusercontent.com/127464474/224496922-69a414a9-caea-48bc-8318-c3f8f94a3565.png)

When clicking on the custom theme "desktop installer" the site changes the visual appearance to look like an installer.
![224460654-8494e977-9818-4a37-999a-f4262aca1520](https://user-images.githubusercontent.com/127464474/224496399-788b7d6d-6aa3-4f35-a195-b5443954f535.png)

custom theme: "chat"
![image](https://user-images.githubusercontent.com/127464474/224497086-18d2ee89-81a3-43cd-9138-6cc7d160d3e3.png)

When clicking on the custom theme "chat" the site changes the visual appearance to look like an chat, bot.
![image](https://user-images.githubusercontent.com/127464474/224502689-94687ae2-cc13-4e16-a8fb-6e2df263f60f.png)

**Describe alternatives you've considered**
- the user of the distrochooser tool could change the color of the tool as  [theme mode: dark, light or custom in distrochooser](https://github.com/distrochooser/distrochooser/issues/240) and the visual appearance of the tool here.
- this issue could make distrochooser a tool out of the curve
- the user has the freedom to choose the appearance of the distrochooser tool

**Additional context**
- [[Suggestion] distrochooser with version bot](https://github.com/distrochooser/distrochooser/issues/211)
- [Compare different linux choice solutions with distrochooser](https://github.com/distrochooser/distrochooser/discussions/243)
- [(question) distrochooser: the solution to the core problem of linux?](https://github.com/distrochooser/distrochooser/discussions/204)
- [(question) the xy paradox in the experience of using distrochooser?](https://github.com/distrochooser/distrochooser/discussions/209)
- [(question) distrochooser version: desktop installer?](https://github.com/distrochooser/distrochooser/discussions/215)
- [theme mode: dark, light or custom in distrochooser](https://github.com/distrochooser/distrochooser/issues/240)
- [choose the linux or linux distro by the graphical interface or not of the installation](https://github.com/distrochooser/distrochooser/issues/234)
- [can distrochooser work offline?](https://github.com/distrochooser/distrochooser/issues/236)
- [Add Prometheus endpoint](https://github.com/distrochooser/distrochooser/issues/244)
- [JSONForm with distrochooser](https://github.com/distrochooser/distrochooser/issues/226)
- [[Suggestion] redesign distrochooser with minimal-ui](https://github.com/distrochooser/distrochooser/issues/198)

**Comment by cmllr** [comment]
Thanks for the suggestion. Currently there is a dark mode in development (#240). I don't think there is the need for more theme options.
