### ISSUE TITLE
Update social links

### ISSUE THREAD

**Issue by cmllr** [distrochooser/distrochooser#254]
- [ ] Add @distrochooser@fosstodon.org to social links

**Comment by laoen** [comment]
add distrochooser newsletter: 
- issues: `https://openrss.org/github.com/distrochooser/distrochooser/issues`
- pull-requests: `https://openrss.org/github.com/distrochooser/distrochooser/pulls`
- discussions: `https://openrss.org/github.com/distrochooser/distrochooser/discussions`

**Comment by cmllr** [comment]
> add distrochooser newsletter with openrss:
> 
>     * issues: `https://openrss.org/github.com/distrochooser/distrochooser/issues`
> 
>     * pull-requests: `https://openrss.org/github.com/distrochooser/distrochooser/pulls`
> 
>     * discussions: `https://openrss.org/github.com/distrochooser/distrochooser/discussions`

I only plan to add direct links to GitHub and social media accounts, no third party services.

**Comment by allonkeyns** [comment]
> I only plan to add direct links to GitHub and social media accounts, no third party services.

*img-before*
![image](https://user-images.githubusercontent.com/129011680/227829115-e1af1905-8686-41a8-917d-f67ccb8afc17.png)

*img-after*
![image](https://user-images.githubusercontent.com/129011680/227830236-e063cb71-e16f-4617-b311-021f8cf8de8d.png)

an idea: Add [twitter.com/distrochooser](https://twitter.com/distrochooser) to social links or nostr, mastodon, matrix, gitpay too.

**Comment by cmllr** [comment]
> > I only plan to add direct links to GitHub and social media accounts, no third party services.
> 
> _img-before_ ![image](https://user-images.githubusercontent.com/129011680/227829115-e1af1905-8686-41a8-917d-f67ccb8afc17.png)
> 
> _img-after_ ![image](https://user-images.githubusercontent.com/129011680/227830236-e063cb71-e16f-4617-b311-021f8cf8de8d.png)
> 
> an idea: Add [twitter.com/distrochooser](https://twitter.com/distrochooser) to social links or nostr, mastodon, matrix, gitpay too.

Thanks. Done. Did not know that this option is available in the organisation profile.

**Comment by leavesranpages** [comment]
> Thanks. Done. Did not know that this option is available in the organisation profile.

an idea: it would be interesting to adopt other social networks. The more people who know distrochooser the better.

**Comment by cmllr** [comment]
> an idea: it would be interesting to adopt other social networks. The more people who know distrochooser the better. For example, there is now a trend towards decentralized social networks. I wonder if it would make sense for distrochooser to have some decentralized social network to receive user feedback without the need for a server.

I tried this, but I don't have the time to properly maintain several social network accounts at once.
