### ISSUE TITLE
Would it be possible to have graphql in distrochooser?

### ISSUE THREAD

**Issue by ghost** [distrochooser/distrochooser#255]
**Is your feature request related to a problem? Please describe.**
I wonder if it would be possible to have graphql in distrochooser. Would it be possible to have graphql in distrochooser?

**Describe the solution you'd like** 
[GraphQL](https://graphql.org/) is a query language for APIs and a runtime for fulfilling those queries with your existing data. GraphQL provides a complete and understandable description of the data in your API, gives clients the power to ask for exactly what they need and nothing more, makes it easier to evolve APIs over time, and enables powerful developer tools.

![image](https://user-images.githubusercontent.com/128771521/227590765-893eda60-19a9-4b0e-830a-468e9d1339be.png)

**Describe alternatives you've considered**
- I didn't find information where I can find the distrochooser api documentation. In that sense, I don't know how I can use some api if I need to.
- My general question would be whether it would be possible to use graphql, which is a very used API query pattern.
- graphql can be used to make the distrochooser experience even more personalized, it could be used for filters or sublayers.
- Is it possible to convert a swagger to graphql.
 
**Additional context**
- [add link to distrochooser API documentation](https://github.com/distrochooser/distrochooser/issues/249)
- [(question) open data and open telemetry in distrochooser?](https://github.com/distrochooser/distrochooser/discussions/225)
- [Compare different linux choice solutions with distrochooser](https://github.com/distrochooser/distrochooser/discussions/243)
- [[Suggestion] Filter search results in distrochooser](https://github.com/distrochooser/distrochooser/issues/217)
- [[Suggestion] metrics for distrochooser](https://github.com/distrochooser/distrochooser/issues/200)
- [Allow user to define the importance of an question based on several criterias](https://github.com/distrochooser/distrochooser/issues/231)
- [[Suggestion] Generate user profile in distrochooser](https://github.com/distrochooser/distrochooser/issues/216)
- [[Suggestion] choose questions about linux distro according to behavioral profile](https://github.com/distrochooser/distrochooser/issues/219)
- [Feedback mode](https://github.com/distrochooser/distrochooser/issues/251)
- [swagger-to-graphql](https://github.com/yarax/swagger-to-graphql)
- [JSONForm with distrochooser](https://github.com/distrochooser/distrochooser/issues/226)

**Comment by cmllr** [comment]
Thanks for the suggestion!

Distrochooser will offer an Prometheus endpoint (see #244), but GraphQL is not planned.
