### ISSUE TITLE
[suggestion] add distrochooser with mirrors: i2p, tor, ipfs, hypercore, dat

### ISSUE THREAD

**Issue by ghost** [distrochooser/distrochooser#257]
**Is your feature request related to a problem? Please describe.**
A general problem with a distrochooser site is that it can be used by many users. If the site goes down, it would not be easy for the user to use it, as its state is offline. 

**Describe the solution you'd like**
I would like to have other versions of distrochooser in case the site crashes or stops working or fail. It is very common to redirect all or any new traffic or massive visits to another server, route, site.  So, a partial solution to solve the above problem is to create mirrors (for example, alternate routes or sites on other network protocols). 

The solution I describe here includes several network protocols, which can be mirrors of the official website.  For example, any user can try to access distrohooser website on other network protocols;
  - i2p:  `/i2p/22222mYwAPJzv22211HdW111111111fffvvvv/distrochooser`
  - tor:  `/onion/22222mYwAPJzv22211HdW111111111fffvvvv/distrochooser`  
  - ipfs: `/ipfs/22222mYwAPJzv22211HdW111111111fffvvvv/distrochooser` 
  - hypercore: `/hypercore/22222mYwAPJzv22211HdW111111111fffvvvv`
  - dat: `/dat/22222mYwAPJzv22211HdW111111111fffvvvv/distrochooser`

**Describe alternatives you've considered**
- A mirror site is a website or set of files on a computer server that has been copied to another computer server so that the site or files are available.
- Unknown or popular browsers may or may not support the network protocols I describe here. Generally, browsers that support these protocols are: [Tor Browser](https://github.com/TheTorProject), [Brave Browser](https://brave.com), [Agregore Browser](https://agregore.mauve.moe/), [Beaker Browser](https://github.com/beakerbrowser). All these browsers are free and open source.
- A general problem with this type of feature request is that it can increase the complexity in managing distrochooser copies.
- Protocols like dat, hypercore, ipfs are p2p.
- A general problem is that people are unaware of these network protocols and may have difficulty using them.
- There are developers who don't like things like tor, i2p, ipfs, dat, hypercore etc.
- There are open source solutions like: [ngosang/trackerslis](https://github.com/ngosang/trackerslist/issues/170) that have this feature that I'm requesting here.

**Additional context**
- This increases the privacy, anonymity and security of distrochooser.
- Users may be interested in using other versions of distrochooser on alternative network protocols like: i2p, tor, ipfs, hypercore, dat.
- The hash examples I have demonstrated or described are invalid examples, they are for demonstration purposes only.
- This increases the availability of the distrochooser site for many people who do not use the google chrome browser, mozilla firefox.
- [TheTorProject](https://github.com/TheTorProject): "Tor Browser prevents someone watching your connection from knowing what websites you visit."
- [hypercore-protocol](https://github.com/hypercore-protocol): "A fast, scalable, and secure peer-to-peer protocol for everyone"
- [brave browser: brave and ipfs](https://brave.com/ipfs-support/):  "Over the past several months, the Brave team has been working with Protocol Labs on adding InterPlanetary File System(IPFS) support in Brave. IPFS is an exciting technology that can help content creators distribute content without high bandwidth costs, while taking advantage of data deduplication and data replication. There are performance advantages for loading content over IPFS by leveraging its geographically distributed swarm network. IPFS is important for blockchain and for self described data integrity. Previously viewed content can even be accessed offline with IPFS! The IPFS network gives access to content even if it has been censored by corporations and nation-states, such as for example, parts of Wikipedia."
- [(question) distrochooser in IPFS?](https://github.com/distrochooser/distrochooser/discussions/206)

**Comment by cmllr** [comment]
This topic has been lengthy discussed on https://github.com/distrochooser/distrochooser/discussions/206. I don't think this is an option for distrochooser.
