### ISSUE TITLE
add translation of pages or routes: "/info/privacy/", "/info/imprint/", "/info/about/"

### ISSUE THREAD

**Issue by ghost** [distrochooser/distrochooser#258]
**Is your feature request related to a problem? Please describe.**
A general problem with the distrochooser site is that it is in en-us. But, most users who can access the site may not know the english language.  Some users may choose native language like ptbr(portuguese-brazil), pt(portuguese), ch(chinese), jp(japanese) etc.

**Describe the solution you'd like**
A possible solution would be to add support for multiple languages which is something that has already been done on the main page, but the subpages do not have translation in another language. This is the problem in context for which I have a possible solution here. 

The before and after images represent what was transformed, altered, modified in the graphical interface.

*img1-before: `https://distrochooser.de/info/privacy/en`*  | *img1-after: `https://distrochooser.de/info/privacy/prefix-languageName`*
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/129122738/228083083-83625df1-d8a6-4238-a0f2-36c5191397fb.png)  | ![image](https://user-images.githubusercontent.com/129122738/228083498-6a67bd10-34ab-4bc1-bb13-360a91b90a8b.png)

*img2-before: `https://distrochooser.de/info/imprint/en`*  | *img2-after: `https://distrochooser.de/info/imprint/prefix-languageName`*
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/129122738/228084209-fd51b782-d601-429f-b4d8-6252a4c5be4c.png) | ![image](https://user-images.githubusercontent.com/129122738/228084418-beba5a4f-7ae2-4c78-8259-b8e1b6aafbe6.png)

*img3-before: `https://distrochooser.de/info/about/en`*  | *img3-after: `https://distrochooser.de/info/about/prefix-languageName`*
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/129122738/228086080-3f59b878-72ba-47b0-adf3-357fc8ec7b6a.png) | ![image](https://user-images.githubusercontent.com/129122738/228086275-55d71b3d-a284-4e52-b590-5d2c0b6dc9d8.png)

**Describe alternatives you've considered**
- The main page was translated, but the subpages were not translated like: 
    - `https://distrochooser.de/info/privacy/prefix-languageName`
    - `https://distrochooser.de/info/imprint/prefix-languageName`
    - `https://distrochooser.de/info/about/prefix-languageName`
- It would be interesting to add a menu for the user to select the text version in other languages.

**Additional context**
*"concept"*
![image](https://user-images.githubusercontent.com/129122738/228085902-2bc6affe-4814-423f-a497-c13adf8d905f.png)

img-description: Here we have routes in several languages ​​like: `https://distrochooser.de/info/privacy/`, `https://distrochooser.de/info/imprint/` and  `https://distrochooser.de/info/about/`

*"source-code"*
`https://distrochooser.de/info/privacy/`, `https://distrochooser.de/info/imprint/` and  `https://distrochooser.de/info/about/`
```html
<div class="language-select">
   <label for="language">language</label>
   <select id="language" title="language">
      <option value="en">English</option>
      <option value="de">Deutsch</option>
      <option value="it">Italiano</option>
      <option value="zh-hans">简体中文</option>
      <option value="zh-hant">繁體中文</option>
      <option value="vn">Tiếng Việt</option>
      <option value="ch">Schwizerdütsch</option>
      <option value="fr">Français</option>
      <option value="ru">русский</option>
      <option value="nl">Dutch</option>
      <option value="he">עברית</option>
      <option value="es">español</option>
      <option value="fi">suomalainen</option>
      <option value="tr">Türkçe</option>
      <option value="pt-br">português brasileiro</option>
      <option value="id">bahasa Indonesia</option>
      <option value="gr">ελληνική γλώσσα</option>
      <option value="pl">Polski</option>
      <option value="sv">svenska</option>
   </select>
</div>
```

**Comment by cmllr** [comment]
Hey, thanks for the suggestion. These pages have a lot of content and require a lot of translations. To keep effort needed for new translation compact, I decided to keep these sides translated only in en and de.
