### ISSUE TITLE
Results Page is Migraine Trigger

### ISSUE THREAD

**Issue by MarjaE2** [distrochooser/distrochooser#259]
**Describe the bug**
The results page has a very wide, non-scrolling sidebar, and lacks any clear visual separation between the sidear and the results, so scrolling or paging down can trigger migraines and motion sickness.

**To Reproduce**
1. Finish the Quiz.
2. Page Down.

**Expected behavior**
I can't say I *expect* web sites to be accessible these days... But having everything scroll together would help, and at the least a narrow sidebar and a clear visual separation from the results would help.

**Screenshots**
![Screen Shot 2023-04-03 at 2 13 04 PM](https://user-images.githubusercontent.com/12875862/229592585-14a8f1b7-d6f7-4fa6-b4b5-77103faf87ae.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.14
 - Browser Firefox
 - Version 111.0.1 with reduce motion, changed fonts, and other accessibility fixes

**Comment by libremarus** [comment]
Hi MarjaE2.

Please see this: [Ask the user the amount of distributions to display as a result](https://github.com/distrochooser/distrochooser/issues/230), [Limit number of distro's shown in results by default](https://github.com/distrochooser/distrochooser/issues/150) 


*idea1: Ask the user the amount of distributions to display as a result*
<img src="https://user-images.githubusercontent.com/129801876/229640490-7e6e1501-b3ab-4506-a6bc-627235005eec.png" alt="image" width="560"/>

*idea2: Limit number of distro's shown in results by default: slideshow(view) 1*
<img src="https://user-images.githubusercontent.com/129801876/229641147-13a10d38-7f66-457e-a671-624ff359f4c9.png" alt="image" width="560"/>

*idea3: Limit number of distro's shown in results by default: kanban(view) 2*
<img src="https://user-images.githubusercontent.com/129801876/229641273-a3dc2936-764f-4669-aca2-dd8fbb273587.png" alt="image" width="560"/>

**Comment by vincivermeer** [comment]
> idea 4: Limit number of distro's shown in results by default: kanban(view) and slideshow(view) 3

an idea: that I find initially interesting would be to have a visual option similar to a slideshow of 4 cards per page. as you hover over the card, the card changes color. And the page number too.

<img src="https://user-images.githubusercontent.com/130012497/230252284-0e51ac6a-1df7-42c3-93ae-ca10e2e8ad75.png" alt="image" width="500"/>

**Comment by cmllr** [comment]
Hey @MarjaE2, thanks for the remark.

I aim to introduce a optical separation between navigation and main content. Do you have further remarks on how to avoid migraine triggers here and how I can improve the UX for affected users? Thanks!

**Comment by cmllr** [comment]
The fixes are implemented and will be released with the next large update (part of #220)
