### ISSUE TITLE
Ubuntu is not recommended because of "third party services"

### ISSUE THREAD

**Issue by jbicha** [distrochooser/distrochooser#271]
I completed the questionnaire at https://distrochooser.de/

One of the results was Ubuntu with this note:

"We cannot recommend this distribution for you because:
— Connects to third party services by default"

I do not believe this is an accurate differentiator from other recommended distros.

I think it is appropriate for me to mention here that I am a Canonical employee who works on Ubuntu Desktop.

**Comment by cmllr** [comment]
This is known and will be fixed with #270.

**Comment by cmllr** [comment]
Update: is fixed. Thanks for the
