### ISSUE TITLE
[question] Where does the data for `AnswerDistributionMatrix` come from?

### ISSUE THREAD

**Issue by arunanshub** [distrochooser/distrochooser#277]
I am unable to figure out the source of data for `AnswerDistributionMatrix`.
 https://github.com/distrochooser/distrochooser/blob/a72c798c8154d5bc3676f8aa3a024f797e072b16/backend/distrochooser/calculations/default.py#L22-L31

And it seems crucial in building consensus and deriving the result.

https://github.com/distrochooser/distrochooser/blob/a72c798c8154d5bc3676f8aa3a024f797e072b16/backend/distrochooser/calculations/default.py#L49-L52

**Comment by cmllr** [comment]
Is your question related to the code or about where the _actual_ data is located? As `AnswerDistributionMatrix` is a model, it's data is located in the database, which is received in line 31 of the first listing.

Regarding the actual data: As currently standing, the data is not open. For the next version, it is planned to include this data in the repository under an open source license.

**Comment by arunanshub** [comment]
That's right. I am referring to the actual data. I am currently experimenting with optimization of the backend (eg, making it serverless, db caching via prisma ORM + prisma accelerate, alternate ways of computing results etc.)

Is there an issue if I could use the data for research and experimentation purposes?

**Comment by cmllr** [comment]
Sorry for my late response, I will consider opening the data in a suitable way for such research and experiments in the future. But I cannot give you an ETA for that, unfortunately.

**Comment by arunanshub** [comment]
Thanks for your reply. How do you propose I should experiment with the application in the meanwhile?

**Comment by cmllr** [comment]
It depends on where your focus is. Do you aim to experiment more on the backend site or  the frontend? I _think_ I could provide a debug version of the database (which is basically just the plain mappings) until I complete the proper way of opening the production data.

**Comment by cmllr** [comment]
The repository https://github.com/distrochooser/matrix-archive-5 is now public. It contains the category, distro and answer result matrix data for the project and can be imported using the Django fixture import mechanisms. The repo is intended for local development and experiments. If you have any questions on using it, please feel free to open a new issue here.
