### ISSUE TITLE
Linux is not an operating system but a kernel

### ISSUE THREAD

**Issue by JeromeSchmied** [distrochooser/distrochooser#278]
Linux is the name of a kernel and not an operating system.

Still, in the third choice on this screenshot,
> I have a good understanding about the Linux operating system

is written. This is incorrect.
![image](https://github.com/distrochooser/distrochooser/assets/118479592/9499deeb-bcab-4fcb-907b-9071a4afae51)

As can be found [here](https://www.gnu.org/gnu/gnu-linux-faq.html), a better alternative goes like this:
> I have a good understanding about GNU/Linux operating systems.

Correcting it would make this great project even better, thanks in advance.

**Comment by cmllr** [comment]
Hey, thanks for the remark! I will update the translation on the next occasion.

**Comment by RasheedAZ** [comment]
Wouldn't Linux-based operating systems be more accurate as Alpine Linux and others are non GNU...?

**Comment by cmllr** [comment]
thanks for these ideas, I think I will stick to "Linux-based operating system" for this context!

**Comment by cmllr** [comment]
I added the change in phrasing to the new translation. It will be applied when the new version goes online. Thank your for your remarks!
