### ISSUE TITLE
You forgot best gaming distro

### ISSUE THREAD

**Issue by ghost** [distrochooser/distrochooser#279]
Isn't Nobara best gaming distro? It made by GloriousEggroll (creator of Proton-GE) with many bug fixes and gaming-oriented updates.
https://nobaraproject.org/

**Comment by StellarHarbour** [comment]
Hey, any progress?

**Comment by cmllr** [comment]
Hello, sorry for my late response.

I am currently focused on creating a new distrochooser version and decision matrix changes will be done afterwards (the currently running version will not receive any major distribution additions anymore).

Your suggestion is on the todo-list and will be evaluated when the core programming is done.
