### ISSUE TITLE
Add open graph tags

### ISSUE THREAD

**Issue by igwigg** [distrochooser/distrochooser#283]
**Is your feature request related to a problem? Please describe.**

It just looks better when sharing the URL on Social Media (Fedi) This is not looking nice: 
![grafik](https://github.com/distrochooser/distrochooser/assets/5790079/e55db6ac-57e5-429e-978b-5583d6a05c19)

**Describe the solution you'd like**
Adding open graph Tags would make it look better

**Describe alternatives you've considered**
Not sure if there are any alternatives for this.

**Comment by cmllr** [comment]
hey @igwigg thank you for your bug report!
On the currently running version I cannot provide a fix. 
The future version was udpated to show the corresponding OGP/ card tags also for language besides de/en with commit https://github.com/distrochooser/distrochooser/commit/a345579dfde2f1046e65a467de1a678b3b880256
