### ISSUE TITLE
Rephrase "I want to configure as much as possible using graphical applications"

### ISSUE THREAD

**Issue by GTcreyon** [distrochooser/distrochooser#284]
**Is your feature request related to a problem? Please describe.**
It's hard to understand and explain what "I want to configure as much as possible using graphical applications" means. My understanding is that it means "If I configure something, I would like to use graphical applications to do it." However, it could also be interpreted to mean "I would like to have graphical applications that give me as many configuration options as possible."

**Describe the solution you'd like**
Rephrase the sentence to reduce ambiguity. Perhaps something like "I prefer to use graphical applications instead of a terminal when configuring my system."

**Comment by cmllr** [comment]
hey @GTcreyon !

Thank your for your suggestion! I rephrased the affected translation based on your feedback! It will come online with the new version, so it may take some time to appear online.
