### ISSUE TITLE
“Usage requires less computer knowledge than answered”

### ISSUE THREAD

**Issue by nclm** [distrochooser/distrochooser#287]
**Describe the bug**
The result page can include the sentence “Usage requires less computer knowledge than answered” which is nonsensical. Less knowledge cannot be *required* to use something. And even someone with high computer knowledge might want something nice and easy to use on an everyday basis.

**To Reproduce**
1. Select “I am already able to solve some computer problems by myself” or “I can troubleshoot most or all computer problems by myself” in “Computer knowledge”.
2. Look at results.

**Expected behavior**
Either:
* No mention of computer knowledge should appear, as the user exceeds the minimal requirement.
* A better phrased sentence about how this distribution is primary meant for users with less computer knowledge, though I do think it’s a weird thing to point out.

**Screenshots**
<img width="590" src="https://github.com/distrochooser/distrochooser/assets/923008/6fcf0f6e-0ffa-4daf-9374-c9e3edcfa706">

**Comment by cmllr** [comment]
hey @nclm thank you for your report!

You are completely right, at the current state this mapping does not make any sense. It will be removed with the next (major) update!
