### ISSUE TITLE
Django Exception: You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path

### ISSUE THREAD

**Issue by theoforger** [distrochooser/distrochooser#318]
### Describe the bug
Related to issue #301.

During the setup process, the following error occurs when collecting static files:

```
django.core.exceptions.ImproperlyConfigured: You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.
```

Setting a STATIC_ROOT in [`settings.py`](https://github.com/distrochooser/distrochooser/blob/main/code/kuusi/kuusi/settings.py) does solve this problem:
https://github.com/distrochooser/distrochooser/blob/85103ec7191d491ceba24bf5868afd7a2c557319/code/kuusi/kuusi/settings.py#L186
For example:
```python
STATIC_ROOT = join(BASE_DIR, 'staticfiles')
```

Not sure if this is intentional. If so, it might be a good idea to mention this in the instructions.

### To Reproduce
1. Clone the repo
2. Follow the instructions in [`SETUP.md`](https://github.com/distrochooser/distrochooser/blob/main/SETUP.md)
3. The issue occurs during this step: 
```bash
# Add static files
python manage.py collectstatic
```

### Environment
 - Fedora Workstation 40
 - Python 3.12.6

**Comment by cmllr** [comment]
hey @theoforger thanks for reporting that. 

You are completely right, the setting of `STATIC_ROOT` was not correct. I've provided an update with https://github.com/distrochooser/distrochooser/commit/4fd3cbf6797351989a734151e9869eaa0440fe05 - can you verify it fixed that issue also on your side?

**Comment by cmllr** [comment]
That also adds a `static_root` folder within the repo root so users's wont have to create that folder for local instances by themselves.

**Comment by theoforger** [comment]
Thanks for the fix! I just tested https://github.com/distrochooser/distrochooser/commit/4fd3cbf6797351989a734151e9869eaa0440fe05 and can confirm that it fixes the issue.

Great project btw! I always send the website to my friends whenever they want to "try that Linux thing of yours on my computer"😂

**Comment by cmllr** [comment]
> Great project btw! I always send the website to my friends whenever they want to "try that Linux thing of yours on my computer"😂

Thank you :)!
