### ISSUE TITLE
Add skip button

### ISSUE THREAD

**Issue by cmllr** [distrochooser/distrochooser#326]
Task:

Add a skip button to pages using the `navigation.html`template. Use the `<button>` element with `button='BTN_NEXT_PAGE_FORCE'`.

The skip button is not displayed on the first page and the last page: `page.previous_page` and `page.next_page` can be used for this. These properties default to `None` if no sites are available.

There is the need to introduce a language value `BTN_SKIP_PAGE` in `ui-en.json` within the language repo.

Definition of done:

- The button is visible as required
- There is a second pull request with the language change

**Comment by georgioupanayiotis** [comment]
i want to take this!

**Comment by cmllr** [comment]
> i want to take this!

Thank you for your interest in contributing. I've assigned you to the issue!

If you have any issues or ideas, feel free to give me a ping.

Just to give a disclaimer, as this happened previously: The current dev version is a server-side Django application and does not utilize a frontend rendering framework (like Vue/ React/ Angular/ you name it) currently.

**Comment by Indrajeet-S** [comment]
hey, I would like to solve this issue!

**Comment by georgioupanayiotis** [comment]
@Indrajeet-S you can have it no prob
