### ISSUE TITLE
Prevent meta_tags from causing a server error if the translation is incomplete

### ISSUE THREAD

**Issue by cmllr** [distrochooser/distrochooser#331]
The function `meta_tags` in `code/kuusi/web/templatetags/web_extras.py` updates texts with "description" in it with the value from the current translation. This causes the issue if `DESCRIPTION_TEXT` is not present in the current translation, the app will result in a server error.

Definition of done:

There should be a check added if the key `DESCRIPTION_TEXT` is present in the currently active translation.

**Comment by shawaiz-khan** [comment]
Can I do this?

**Comment by cmllr** [comment]
> Can I do this?

thanks for your interest in contributing! I am  currently in discussion with @Indrajeet-S about a related ticket, so I think he will work on this for now, as he is currently working on #313 aswell - which makes a bit easier to handle.

There are plenty of issues currently tagged for hacktoberfest - https://github.com/distrochooser/distrochooser/milestone/4 - feel free to take look if something looks interesting (you can of course provide ideas for additions!). If you have any further ideas, feel free to join the project discord or start a discussion here in Github. Thank you!

**Comment by shawaiz-khan** [comment]
Thank You

**Comment by Indrajeet-S** [comment]
Hey,  If the key `DISCRIPTION_TEXT`is not present, what we need to do from the following two:
1) set a default description text or 
2) skip the update to prevent a server error
@cmllr

**Comment by cmllr** [comment]
For the record: Currently, the focus is on preventing the server error, so focusing on the second option, thank you!

**Comment by Indrajeet-S** [comment]
Hey @cmllr I made a PR, kindly review it and let me know the verdict!

**Comment by cmllr** [comment]
Closed with #333
