### ISSUE TITLE
Bad link for SolusOS

### ISSUE THREAD

**Issue by Julien684** [distrochooser/distrochooser#340]
**Describe the bug**

**To Reproduce**
1. Go to [https://distrochooser.de/fr/d5329784f5bc/](https://distrochooser.de/fr/d5329784f5bc/)
2. Click on 'Site web de la distribution' for Solus website.

**Expected behavior**
How to get to the distribution website.

**Desktop (please complete the following information):**
 - OS: SolusOS KDE
 - Browser Firefox
 - Version 133

**Smartphone (please complete the following information):**
 - Device: Fairphone 4
 - OS: /e/OS
 - Browser Firefox
 - Version 133

**Additional context**
The right link is [https://getsol.us](https://getsol.us).

**Comment by cmllr** [comment]
Thank you for your report, the link has been updated!
