### ISSUE TITLE
Void linux supports 32 bit

### ISSUE THREAD

**Issue by shak-mar** [distrochooser/distrochooser#55]
I successfully use void linux on an i686 machine, but the 64-bit-required answer for void linux says it's not possible.  Please change that ;)

There's no official reply in here, but relevant: https://forum.voidlinux.eu/t/void-linux-32-bit-x86-support-in-the-future/2417

**Comment by cmllr** [comment]
Thank you very much for your reply! I've updated the distribtion matrix!
