### ISSUE TITLE
Unable to move from first page in distrochooser.de

### ISSUE THREAD

**Issue by reikdas** [distrochooser/distrochooser#57]
OS - Windows 10
Browsers tested on - Firefox(latest stable), Chrome(latest stable)

https://distrochooser.de/en just shows the Welcome to Distrochooser! page with no questions or buttons to click except contact and privacy.

**Comment by cmllr** [comment]
Hey @reikdas 

thank you for your report! 

I think it should by fixed (for now). I close this issue here and continue commenting on https://github.com/distrochooser/waldorf/issues/1, because this is a backend related issue.

**Comment by reikdas** [comment]
It is working now. Thanks!
