### ISSUE TITLE
Installation: Hardware support question

### ISSUE THREAD

**Issue by martok22** [distrochooser/distrochooser#58]
The 6th question gives you two choices: you know your system supports 64 bit, or you don't know/are not sure about compatibility. It's missing an option for computers that support only 32 bit oss.

**Comment by cmllr** [comment]
The answer "I'm not sure about this and/ or my computer already has performance issues. " leads to 32 bit compatible distros. But I think I may update the wording on the next major update

**Comment by cmllr** [comment]
Will be fixed with version 5 release. Thanks again for the feedback!
