### ISSUE TITLE
Add MX Linux to list of possible recommended distros

### ISSUE THREAD

**Issue by Maddosaurus** [distrochooser/distrochooser#59]
[MX Linux](https://mxlinux.org/current-release-features) seems to be an interesting possible addition to distrochooser.  
They still release 32-bit images, which is especially interesting for legacy/low-end hardware.  
It is based on Debian with backports (and flatpak support) with a themed XFCE as desktop environment.  
Their speciality is the plethora of additional tools to ease common daily tasks (beginner friendly, whilst not hiding away the full customization).  
To quote them: *MX Linux is a cooperative venture between the antiX and former MEPIS communities, using the best tools and talents from each distro. It is a midweight OS designed to combine an elegant and efficient desktop with simple configuration, high stability, solid performance and medium-sized footprint.*  

It could extend the 32-bit results in distrochooser and provide an additional choice for an entry-level Linux, which could help a lot of people.

Thanks in advance!

**Comment by cmllr** [comment]
Is added in current release
