### ISSUE TITLE
database for own calculations

### ISSUE THREAD

**Issue by SpiritInAShell** [distrochooser/distrochooser#61]
I'd love to filter the raw data to my needs. I believe that distrochooser does great work, still sometimes I'd like to fine tune.

I remember having seen the datasets somewhere but I couldn't find them here in the repo nor anywhere else. Maybe I am remembering ghosts and it was not available at all.

I hope opening an issue for this question is appropriate.

Thanks!

**Comment by cmllr** [comment]
Hey, 

I'm sorry but I won't release the database.

With best regards,
Christoph
