### ISSUE TITLE
Additional Info does not show up in the hardware question

### ISSUE THREAD

**Issue by PositiveKoodoo** [distrochooser/distrochooser#70]
While looking into the localization files, I saw that there is additional information to the hardware question.
I so far have not found a way to see this additional information on the beta-website itself.
I use Chrome, in case that that's relevant.

**Comment by PositiveKoodoo** [comment]
Addendum: The same happens with the ideology-question.

**Comment by PositiveKoodoo** [comment]
Okay, I now realized that I'm stupid and the additional information is being shown, you just have to click the little ?.
I'd probably put this closer to the question itself, so that it's a little bit clearer.

**Comment by cmllr** [comment]
![grafik](https://user-images.githubusercontent.com/2878201/66272763-2a958780-e86e-11e9-83ef-d3e315d37793.png)
