### ISSUE TITLE
Translation status

### ISSUE THREAD

**Issue by cmllr** [distrochooser/distrochooser#82]
Following translations are either completed or not assigned to anyone. If you wan't to contribute to a translation, comment on this issue. 

- [X] German
- [X] English
- [X] Italian Done by @jollypuppet 
- [X] Simplified Chinese Done by @xingjiapeng
- [X] Vietnamese Done by @streetsamurai00mi 
- [X] Traditional Chinese Done by @explorer422
- [X] French Done by @NathanBnm
- [X] Russian Done by @jalovisko 
- [X] Dutch Done by @henrydenhengst 
- [X] Hebrew Done by @omeritzics 
- [X] Spanish Done by @pabloab 
- [x] Polish
- [ ] Japanese

> Comment to list further (in progress) translations

All translations are `po`-files inside of `backend/locales`.

Thank you 😄

**Comment by jollypuppet** [comment]
Hi, I can help with the Italian translation.

**Comment by cmllr** [comment]
Thank you @jollypuppet!

I added the contributing guide https://github.com/distrochooser/distrochooser/blob/master/CONTRIBUTING.md for more information about how to make the translations.

Give me a ping if you need any informations!

**Comment by NightStary** [comment]
Hello! I would help you with Russian translation. :)

**Comment by cmllr** [comment]
@NightStary sounds great, thank you!

If you need any infos, just ping me in this thread!

**Comment by marklin0913** [comment]
Hi. I would like to contribute to Traditional Chinese. The current Chinese Translation is Simplified Chinese.

**Comment by cmllr** [comment]
Hey @explorer422, thank you for your interest in contributing!

If you have any questions while working on the translation, just give me a ping!

**Comment by gnu-ewm** [comment]
Hi. I would like to add Polish translations.

**Comment by NathanBnm** [comment]
Hi. I would be glad to work on French translation.

**Comment by NathanBnm** [comment]
@cmllr French is done via #113

**Comment by mathwar** [comment]
Hi @cmllr, I'm working on a spanish translation. I will try to improve as much as possible from oldv4.

**Comment by henrydenhengst** [comment]
I can help with Dutch translations. Just let me know.

**Comment by msmafra** [comment]
Hello there.
I can help with Brazilian Portuguese translation

**Comment by cmllr** [comment]
@msmafra thank you for your intention to contribute an translation. If you have any questions, feel free to open an issue and give me a ping!

**Comment by msmafra** [comment]
> @msmafra thank you for your intention to contribute an translation. If you have any questions, feel free to open an issue and give me a ping!

Hello there. So many things happened, I forgot to contact you.

**Comment by bino-faata** [comment]
Hey. I can help with ukrainian translation

**Comment by pabloab** [comment]
You could translate [`en.po`](https://github.com/distrochooser/distrochooser/blob/master/backend/locale/en.po) into a `uk.po`. I did it automatically ([attached](https://github.com/distrochooser/distrochooser/files/8236781/uk.zip)). You could review it, fix any issues and then create a PR.

**Comment by pabloab** [comment]
@bino-faata You could translate [`en.po`](https://github.com/distrochooser/distrochooser/blob/master/backend/locale/en.po) into a `uk.po`. I did it automatically ([attached](https://github.com/distrochooser/distrochooser/files/8236807/uk.zip)). You could review it, fix any issues and then create a PR.

**Comment by nkot56297** [comment]
I found this initiative very interesting, I want to help by translating from English to pt-br - portuguese-brazilian.

**Comment by nkot56297** [comment]
Hello everyone!

1. An idea, I don't know if this idea is a good one - I was thinking of creating a program for people to migrate to some linux distro... my idea would be to create a graphical interface where the user would choose according to certain criteria a linux distribution to be installed on your machine.
2. This may be possible without the need for a hardware manufacturer or company. Also, it would be possible to do this without the need for a bootable USB stick.
3. My idea here would be to use wsl - which is a feature of Windows 10 and Windows 11 that has native support for linux to make this migration from one operating system to another without major problems.
4. How would you do it?
   - My idea is to create a background script that configure or install the preferred linux distro through wsl.
   - After that, the script asks the user through a graphical interface where are the files that you want to backup, save.
   - After this question, the script takes the user data and saves it in the partition that the linux distro via wsl was configured.
5. When the user restarts the machine, the script installs the preferred linux distribution and after installing the preferred linux distribution - the script creates a partition called backup with the data that the user wanted to save and backup at the beginning.
6. The main advantage of this is that you would not need to have a bootable flash drive or ask a manufacturer or hardware company to install linux on your machine, this would be automatic at least on computers with windows 10 and windows 11.
7. Did I say something bad? something wrong? Can anyone criticize this idea? What do you think of this alternative to install linux automatically for regular users or home users or end users?

I want to hear feedbacks, criticisms from everyone!

**Comment by cmllr** [comment]
thank you all for your intent to provide translations to the service! Please let me know if you need any information to create the translations :)

**Comment by nkot56297** [comment]
@cmllr here https://github.com/nkot56297/distrochooser

**Comment by nkot56297** [comment]
@cmllr Thank you so much for accepting the pull request, I'm happy to help ;D

**Comment by bodamat** [comment]
I'm interested to help with Ukrainian translation :)
As I understand I just need to use boilerplate en.po and then I will do a pull request

**Comment by cmllr** [comment]
There is now a Weblate instance for distrochooser: https://translate.distrochooser.de (as mentioned on https://github.com/distrochooser/distrochooser/issues/190#issuecomment-1328237249).  

You can still add translations via pull request, but If desired, you can use the Weblate instance for this work (please note the GDPR remarks on https://github.com/distrochooser/translations#weblate-on-translatedistrochooserde).

I will close this issue for now as the overview of translations can now be seen on https://translate.distrochooser.de/projects/distrochooser/translations/
